### ISSUE TITLE
Handlers with severities not including OK still handle OK

### ISSUE THREAD

**Issue by sstarcher** [sensu/sensu#991] opened 2015-07-09 14:22 UTC
I have a handler with the severities of ["critical"] and resolved checks of OK still come through the handler.

**Comment by portertech** [comment] 2015-07-09 22:59
This will happen if the event action is "resolve". Intended behavior.

**Comment by sstarcher** [comment] 2015-07-10 15:20
Any recommended solution for handling spam from dependent checks on a check resolution.  We have a check for graphite server and we have a lot of checks that use graphite.  We use check dependencies to suppress the failures accessing graphite, but when it comes back online we get spam from the "resolve"

**Comment by calebhailey** [comment] 2016-04-09 18:17
Here's the code confirming @portertech's comments indicating that severity filtering is intentionally ignored for "resolve" action events: https://github.com/sensu/sensu/blob/a17c29c85364b7dc3cb6d8ca4600fddd1e0b62fd/lib/sensu/server/filter.rb#L139-L168 

@sstarcher: I haven't tested this but I wonder if a filter could do the trick? 

```
{
  "filters": {
    "example_resolve_filter": {
      "negate": true,
      "attributes": {
        "action": "resolve",
        "check": {
          "dependencies": [
            "your_graphite_check"
          ]
        }
      }
    }
  }
}
```

In this example, this filter would only negate events that have defined check `dependencies` on whatever your graphite check is called, so it wouldn't filter other resolve events. 

In any case, because the severity filtering behavior is actually by design, I'm going to go ahead and close this... it's not a bug. Please don't hesitate to create a new issue if you identify a bug or have a related feature request. 

#monitoringlove

**Closed by calebhailey** 2016-04-09 18:17 UTC
