### ISSUE TITLE
Sensu with JRuby?

### ISSUE THREAD

**Issue by razb** [sensu/sensu#1111] opened 2015-11-17 21:09 UTC
Is anyone using Sensu with JRuby. If so, are there any guidelines or available docs?

**Comment by portertech** [comment] 2015-11-18 02:58
@razb Sensu Core no longer uses a patched version of the EventMachine library, it's now on the updated upstream and works great! Unfortunately, the upstream EM Java reactor lacks support for many things and has a few bugs that need to be fixed. I have plans to push many of the `sensu-em` EM Java reactor changes to the upstream EM project, as that project now has signs of life. The Sensu Core API uses Thin, which does not work on JRuby https://github.com/sensu/sensu/blob/master/lib/sensu/api/process.rb#L6-L9, so an alternative must be used.

**Comment by razb** [comment] 2015-11-27 06:05
I've loaded all the appropriate gems, however when I attempt to start sensu-server under JRuby I get an error:

<pre>NotImplementedError: fork is not available on this platform
           fork at org/jruby/RubyKernel.java:1728
      daemonize at /opt/jruby/lib/ruby/gems/shared/gems/sensu-0.21.0-java/lib/sensu/daemon.rb:258
  setup_process at /opt/jruby/lib/ruby/gems/shared/gems/sensu-0.21.0-java/lib/sensu/daemon.rb:119
     initialize at /opt/jruby/lib/ruby/gems/shared/gems/sensu-0.21.0-java/lib/sensu/daemon.rb:49
     initialize at /opt/jruby/lib/ruby/gems/shared/gems/sensu-0.21.0-java/lib/sensu/server/process.rb:34
            run at /opt/jruby/lib/ruby/gems/shared/gems/sensu-0.21.0-java/lib/sensu/server/process.rb:22
          <top> at /opt/jruby/lib/ruby/gems/shared/gems/sensu-0.21.0-java/exe/sensu-server:10
           load at org/jruby/RubyKernel.java:957
          <top> at /opt/sensu/bin/sensu-server:23</pre>

Reading through the code, it appears that it should detect that I am running JRuby and utilize posix_spawn instead of fork?

Is there a step that I missed?

**Comment by portertech** [comment] 2015-11-27 06:08
@razb JRuby is not a supported platform for Sensu Core. Sensu Enterprise has it's own process daemonization bits etc. Perhaps try running the sensu-server without `-b`, as it is likely the cause of your error.

**Comment by portertech** [comment] 2015-12-04 23:57
JRuby is not a targeted platform for Sensu Core. Going to close this issue out.

**Closed by portertech** 2015-12-04 23:57 UTC
Labels: Won't Fix/Implement
