### ISSUE TITLE
transport config merge results in ["redis","rabbitmq"]

### ISSUE THREAD

**Issue by TJC** [sensu/sensu#1325] opened 2016-06-09 07:38 UTC
My config looks like this, yet sensu appears to end up merging the default transport, rabbitmq, in as well.

```
# cat /etc/sensu/conf.d/transport.json
{
    "transport": {
        "name": "redis",
        "reconnect_on_error": true
    }
}
```

```
# grep transport /var/log/sensu/sensu-api.log
{
  "timestamp":"2016-06-09T17:33:43.596812+1000",
  "level":"warn",
  "message":"config file applied changes",
  "file":"/etc/sensu/conf.d/transport.json",
  "changes":{"transport":{"name":["rabbitmq","redis"]}}
}
```

**Comment by cwjohnston** [comment] 2016-06-09 17:41
Hi @TJC, this seems rather strange. 

I did a bit of manual testing, isolated to the `deep_merge` method which Sensu uses when loading configs, and I couldn't reproduce similar behavior there:

```
# /opt/sensu/embedded/bin/pry
[1] pry(main)> require 'sensu/utilities'
=> true
[2] pry(main)> include Sensu::Utilities
=> Object
[3] pry(main)> deep_merge({ :transport => ["redis"] }, { :transport => "rabbitmq" })
=> {:transport=>"rabbitmq"}
[4] pry(main)> deep_merge({ :transport => "rabbitmq" }, { :transport => ["redis"] })
=> {:transport=>["redis"]}
```

Only by providing a pair of array values did I arrive at the configuration you're reporting:
```
[5] pry(main)> deep_merge({ :transport => ["rabbitmq"] }, { :transport => ["redis"] })
=> {:transport=>["rabbitmq", "redis"]}
```

What version of Sensu are you using? If you are on 0.23 you should be able to run sensu with a `--print_config` flag which will show step-by-step processing of your sensu config and may help to isolate where you may have duplicated transport attributes in your config files.

**Comment by TJC** [comment] 2016-06-10 01:25
HI,
I'm on 0.24.1, installed fresh from the Sensu apt repo yesterday.

grep transport /etc/sensu/conf.d/* returns just one occurrence, transport.json above.

I'm afraid more debugging will have to wait until Tuesday AEST; I've left the office for a four-day holiday as of now :)

**Comment by TJC** [comment] 2016-06-14 01:52
Hi, I've run sensu with the --print_config flag.

It confirms your testing with deep_merge() -- the final result of transport is just:
``` json
"transport":{
    "name":"redis",
    "reconnect_on_error":true
  }
```

However during loading, sensu-api still prints this message, so there seems to be a bug in the log output?

```json
{"timestamp":"2016-06-14T11:50:35.408066+1000","level":"warn","message":"config file applied changes","file":"/home/tobyc/tmp/transport.json","changes":{"transport":{"name":["rabbitmq","redis"]}}}
```

**Comment by cwjohnston** [comment] 2016-06-14 19:58
@TJC actually I believe this output is as intended. The settings loader provides this output in order to illustrate the difference between the running config and the newly merged configuration. See https://github.com/sensu/sensu-settings/blob/v5.2.0/lib/sensu/settings/loader.rb#L111-L117.

**Comment by TJC** [comment] 2016-06-15 00:06
Ah, ok. I'm sorry to have wasted your time. Happy for you to close this issue now.

Although, note that the logs intention was not clear from the actual log message.

**Comment by cwjohnston** [comment] 2016-06-15 03:59
@TJC sorry for the confusion, I'll make a note that we can do better at illustrating the results of configuration loading.

**Closed by cwjohnston** 2016-06-15 03:59 UTC
