### ISSUE TITLE
Sensu-install plugins: Permission denied

### ISSUE THREAD

**Issue by kobbe** [sensu/sensu#1173] opened 2016-02-24 22:44 UTC
To make our file system a bit more secure we have changed our umask to 077. This poses the problem that installing new plugins with Sensu gives permission denied when trying to run them from sensu. i.e the downloaded ruby files need to have read permissions. I now manually add read rights to the files in `/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/` and `/opt/sensu/embedded/bin/`. I also got an error on some old plugins `Permission denied @ rb_sysopen - /opt/sensu/embedded/lib/ruby/gems/2.2.0/specifications/tzinfo-1.2.2.gemspec`after I downloaded a new plugin so it seems like those files are updated or something.

Installation command:
`sudo sensu-install -p network-checks`

**Comment by runningman84** [comment] 2016-03-03 13:53
This is the same issue
https://github.com/sensu/sensu/issues/1168
The sensu install command and the chef sensu_gem resource do not like a secure default umask.

**Comment by calebhailey** [comment] 2016-04-06 22:46
Closing as duplicate of #1168

**Closed by calebhailey** 2016-04-06 22:46 UTC
