### ISSUE TITLE
Keepalive false alert because of time jump in logs

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1929] opened 2018-12-10 12:46 UTC
Hello

when we **restart** a VM with sensu-client we getting critical alerts (configured after 180s) even when the machine reboot takes less that a minute. In the sensu-client logs we can see that the time jumps 7 hours which we believe its related to that false alert. Also to mention that the servers time its set to UTC+7. The time of the server is properly set and ntpd is running, so we can rule out actually time issues on the server itself. 

In uchiwa we can also see that the error code imidiatly jumps from 0 -> 2. The warning which is a 1 is not even shown.

![image](https://user-images.githubusercontent.com/25243862/49733449-1fa4b180-fcb4-11e8-8e89-ad1a2b8362d8.png)
 

When restarting just the sensu service we dont see this behavior.

`{"timestamp":"2018-12-10T19:07:15.364580+0700","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2018-12-10T19:07:15.364736+0700","level":"warn","message":"stopping"}
{"timestamp":"2018-12-10T19:07:15.365169+0700","level":"info","message":"completing checks in progress","checks_in_progress":[]}
{"timestamp":"2018-12-10T19:07:15.866074+0700","level":"info","message":"closing client sockets"}
{"timestamp":"2018-12-10T19:07:15.874649+0700","level":"warn","message":"stopping reactor"}
{"timestamp":"2018-12-10T12:09:03.391646+0700","level":"warn","message":"config file does not exist or is not readable","file":"/etc/sensu/config.json"}
{"timestamp":"2018-12-10T12:09:03.393511+0700","level":"warn","message":"ignoring config file","file":"/etc/sensu/config.json"}
{"timestamp":"2018-12-10T12:09:03.393562+0700","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2018-12-10T12:09:03.393603+0700","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/rabbitmq.json"}
{"timestamp":"2018-12-10T12:09:03.393635+0700","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/client.json"}
{"timestamp":"2018-12-10T12:09:03.393688+0700","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/client.json","changes":{"client":{"name":["as-propp-3b49.agprod2.agoda.local","as-propp-3b49"],"keepalive":[null,{"handlers":["default","keepalive"],"thresholds":{"critical":180,"warning":120}}],"subscriptions":[null,["linuxvm","adp_forwarder_2.4.1","as-propp-3b49"]]}}}
{"timestamp":"2018-12-10T12:09:03.393729+0700","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/adp_uforwarder.json"}
{"timestamp":"2018-12-10T12:09:03.393761+0700","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/adp_uforwarder.json","changes":{}}
{"timestamp":"2018-12-10T12:09:03.393793+0700","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/devops_consul-client.json"}
{"timestamp":"2018-12-10T12:09:03.393824+0700","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/devops_consul-client.json","changes":{}}
{"timestamp":"2018-12-10T12:09:03.393863+0700","level":"warn","message":"applied sensu client overrides","client":{"name":"xxx","address":"10.46.178.145","keepalive":{"handlers":["default","keepalive"],"thresholds":{"critical":180,"warning":120}},"subscriptions":["linuxvm","xxxx","as-propp-3b49","consul-client-linux","client:xxx"]}}
{"timestamp":"2018-12-10T12:09:03.399812+0700","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
{"timestamp":"2018-12-10T12:09:03.399888+0700","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2018-12-10T12:09:10.280473+0700","level":"info","message":"received check request","check":{"command":"/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/http/check-http.rb -u http://localhost:8500/v1/health/node/$(hostname) --noproxy --query 'Agent alive and reachable' --response-code 200","handle":true,"handlers":["logstash","opsgenie"],"standalone":false,"refresh":900,"occurrences":3,"dependencies":["keepalive"],"tags":["it-devops-configuration","consul"],"owner":"it-devops-configuration","service":"consul","severity":"high","aggregate":false,"addInfo":"Please slack it-devops consul team: #devops_consul_monitor","name":"consul-sevice-check-linux","issued":1544443750}}
{"timestamp":"2018-12-10T12:09:10.505206+0700","level":"info","message":"publishing check result","payload":{"client":"xxx","check":{"command":"/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/http/check-http.rb -u http://localhost:8500/v1/health/node/$(hostname) --noproxy --query 'Agent alive and reachable' --response-code 200","handle":true,"handlers":["logstash","opsgenie"],"standalone":false,"refresh":900,"occurrences":3,"dependencies":["keepalive"],"tags":["it-devops-configuration","consul"],"owner":"it-devops-configuration","service":"consul","severity":"high","aggregate":false,"addInfo":"Please slack it-devops consul team: #devops_consul_monitor","name":"consul-sevice-check-linux","issued":1544443750,"executed":1544418550,"duration":0.224,"output":"CheckHttp OK: 200, found /Agent alive and reachable/ in 259 bytes\n","status":0}}}
{"timestamp":"2018-12-10T19:09:17.575396+0700","level":"info","message":"received check request","check":{"handle":true,"standalone":false,"refresh":900,"dependencies":["keepalive"],"command":"/etc/sensu/plugins/linux/check-procs.rb --pattern 'nscd' --critical-under 1 --critical-over 1","occurrences":3,"service":"linux_basic_checks","owner":"it-infra-external","severity":"high","aggregate":false,"name":"linux-nscd-process","issued":1544443757}}`

## Your Environment

* Sensu version used: 1.6.1
* Active Sensu extensions (e.g. WizardVan 0.1.0): None
* Operating System and version (e.g. Ubuntu 14.04): CentOS7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2):

**Comment by ChrisOnToure** [comment] 2018-12-11 03:39
Quick update, we tried some different versions on the client but the issue persist.

1. Client: 1.6.1 & Server: 1.6.1
2. Client: 1.0.2 & Server: 1.6.1

**Comment by cwjohnston** [comment] 2019-01-14 20:47
hi @ChrisOnToure , thanks for raising this issue.

> In the sensu-client logs we can see that the time jumps 7 hours which we believe its related to that false alert.

The timestamp in each entry in your sensu-client.log is generated based on the system clock. As a result, if the logged time is incorrect, it is because the system clock is incorrect. 

> The time of the server is properly set and ntpd is running, so we can rule out actually time issues on the server itself.

It is my understanding that by default ntpd will avoid changing the system clock in large increments of time, instead preferring to drift the clock forward or backward toward the time reported by the ntp server or server pool in use. See https://askubuntu.com/a/26940 for one explanation of this.

With the above in mind, I submit that your VM is starting up with a system clock time that its significantly skewed from the current wall clock time, and ntp is doing it's job to correct this, but the correction is taking longer than you expect.

Since this all sounds like expected behavior, I am inclined to close this issue. Please let me know if I have misunderstood. Otherwise we'll close this in our next backlog grooming.

**Closed** 2019-01-29 19:24 UTC
