### ISSUE TITLE
Invalid 'Date' entry in Release file

### ISSUE THREAD

**Issue by Buzut** [sensu/sensu#1528] opened 2017-01-12 17:18 UTC
On Ubuntu 16.04, there's an error when trying to update:

```
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/sensu.global.ssl.fastly.net_apt_dists_sensu_Release
E: Failed to fetch https://sensu.global.ssl.fastly.net/apt/dists/sensu/Release  Invalid 'Valid-Until' entry in Release file /var/lib/apt/lists/partial/sensu.global.ssl.fastly.net_apt_dists_sensu_Release
```

**Comment by law** [comment] 2017-01-12 19:23
Duplicate of #1526 - I've even got a workaround in there for ya :-)

**Comment by cwjohnston** [comment] 2017-01-12 20:54
We believe this is now resolved (see https://github.com/sensu/sensu/issues/1526#issuecomment-272277678). Closing.

**Closed by cwjohnston** 2017-01-12 20:54 UTC

**Comment by Buzut** [comment] 2017-01-13 14:38
Works perfectly now thanks :)
