### ISSUE TITLE
clearing all silences for subscription not working

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu#1915] opened 2018-10-16 18:37 UTC
The API documentation seems to indicate it should be possible to clear all silences from a single subscription or check  via a single call to the slienced/clear endpoint.   

## Expected Behavior
`curl -s -i -X POST -H 'Content-Type: application/json' -d '{ "subscription": "stest" }' http://localhost:4567/silenced/clear`

Should clear all siliences for subscription 'stest' 

`curl -s -i -X POST -H 'Content-Type: application/json' -d '{ "check": "stest" }' http://localhost:4567/silenced/clear`

Should clear all siliences for check 'stest' 

## Current Behavior
`curl -s -i -X POST -H 'Content-Type: application/json' -d '{ "subscription": "stest" }' http://localhost:4567/silenced/clear`

`curl -s -i -X POST -H 'Content-Type: application/json' -d '{ "check": "stest" }' http://localhost:4567/silenced/clear`

each return 404

`curl -s -i -X POST -H 'Content-Type: application/json' -d '{ "subscription": "stest", "check" : "stest" }' http://localhost:4567/silenced/clear`

returns 204

## Possible Solutions
1) Make it possible to clear multiple siliences by subscription or check.
2) Update API documentation to make it clearer that API clear endpoint can only be used to clear a single silience percall  and that "check" and "subscription" must both exist together if "id" is not used.

## Steps to Reproduce (for bugs)
1) create silence
`curl -s -i -X POST -H 'Content-Type: application/json' -d '{ "subscription": "stest", "check": "stest", "expire": 9600 }' http://localhost:4567/silenced`

2) confirm exists
`curl -s -X GET http://localhost:4567/silenced | jq .`

3)  attempt to clear all silences for subscription
`curl -s -i -X POST -H 'Content-Type: application/json' -d '{ "subscription": "stest" }' http://localhost:4567/silenced/clear`

4) confirm still exists
`curl -s -X GET http://localhost:4567/silenced | jq .`

5) attempt to clear all silences for check
`curl -s -i -X POST -H 'Content-Type: application/json' -d '{ "check": "stest" }' http://localhost:4567/silenced/clear`

6) confirm still exists
`curl -s -X GET http://localhost:4567/silenced | jq .`

7) attempt to clear silence match check and subscription
`curl -s -i -X POST -H 'Content-Type: application/json' -d '{ "subscription": "stest", "check" : "stest" }' http://localhost:4567/silenced/clear`

8) confirm removed
`curl -s -X GET http://localhost:4567/silenced | jq .`

## Context
User popped up community slack help channel with question on API intent to provide mechanism to clear multiple silences match subscription.

## Your Environment
Centos 7  
tested on Sensu 1.4.3 and Sensu 1.5.0

**Comment by apaskulin** [comment] 2018-10-23 21:36
Thanks, @jspaleta! Moved to https://github.com/sensu/sensu-docs/issues/829 for docs clarification.

**Comment by cwjohnston** [comment] 2018-10-23 21:57
hey @jspaleta, thanks for raising this issue. Wildcards in silencing entry IDs tend to be confusing because they look like, but don't necessarily act like, globing expressions we've come to understand from the shell.

As I believe this expected behavior, we're going to treat this a documentation bug. We've "migrated" this to https://github.com/sensu/sensu-docs/issues/829 and I will now close this issue.

**Closed by cwjohnston** 2018-10-23 21:57 UTC
