### ISSUE TITLE
Can we make the spawn process limit configurable?

### ISSUE THREAD

**Issue by ctheune** [sensu/sensu#1002] opened 2015-07-20 18:17 UTC
Hi,

I'm experimenting only at the moment but I'm running a bazillion lightweight checks and I see that I'm getting limited by the number of number spawnable processes (hardcoded to 12 in sensu-spawn).

My ruby isn't much good and this isn't urgent at all, but I'd like to know if you think this would be worthwhile. Maybe I can contribute in the future, but I'd also appreciate a patch if you think this is reasonable and easy to fix. 

Cheers and thanks for the awesome stuff!

Christian

**Comment by portertech** [comment] 2015-07-20 18:20
@ctheune is the combined execution time great enough to create a backlog? How many checks are being scheduled for execution within such a tight time frame?

**Comment by ctheune** [comment] 2015-07-20 18:22
I'm probably being silly here. :)

I'm scheduling 1500 checks every 60 seconds (using nagios check_http), so, yeah, this creates a backlog because that list of URLs (I just took the top few thousands from Alexa) will contain things that have network issues and thus make check_http hang.

Nevertheless, configurable might be nice. :)

**Comment by ctheune** [comment] 2015-07-20 18:22
From a resource perspective this should be feasible, though. None of my resources (CPU, memory, disk, network, ...) are satured in any way.

**Comment by portertech** [comment] 2015-07-20 19:41
@ctheune I think making it configurable in the client definition is reasonable, going to label this issue as a feature :+1:

**Comment by ctheune** [comment] 2015-07-20 21:04
Great, thanks. :)

**Comment by calebhailey** [comment] 2016-04-09 17:50
#1184 is a duplicate of this, which we tagged for release in 0.24, so I'll do the same here and we'll close both of these at the same time.

**Comment by portertech** [comment] 2016-05-17 01:38
https://github.com/sensu/sensu/pull/1265 made the spawn limit configurable :+1:

**Closed by portertech** 2016-05-17 01:38 UTC
Labels: Feature, Small
