### ISSUE TITLE
Handler severities not being honored

### ISSUE THREAD

**Issue by 29lines** [sensu/sensu#1649] opened 2017-04-05 11:49 UTC
We have a handler that sends emails -- known as "mailer". The severities for the handler are ok, critical, and warning, however emails are still being sent out when the check returns unknown (3).

## Expected Behavior
When a check returns an unknown status the mailer handler should not trigger as configured.

## Current Behavior
Mailer handler triggers and email notification when an unknown status is returned by a check

## Steps to Reproduce (for bugs)
1. Create a handler to ignore unknown events
2. Cause a check to return unknown
3. Watch the handler trigger anyway

## Context
The goal is to not spam our team with emails when the hosts running Sensu start acting up. Occasionally we run into an issue where a few of our Docker hosts run out of resources and start throwing "resource unavailable" errors, which in turn causes sensu checks being run on containerized sensu-clients to return "unknown" check result codes.

Ideally the mailer handler we have configured would just throw those out, but team members are instead getting these messages.

Handler in question:

```
{
    "mailer": {
        "admin_gui": "http:\/\/uchiwa.domainz.local:3000\/",
        "mail_from": "sensu@example.com",
        "mail_to": "alerts@example.com",
        "smtp_address": "smtp.domainz.local",
        "smtp_port": "25",
        "smtp_domain": "domainz.local",
        "template": "\/opt\/sensu-plugins\/handlers\/notification\/generic_template.html.erb",
        "content_type": "html",
        "clients": {
            "example": "bob@bobbertsons.com",
            "jim": "jimbo@gymbo.com"
        }
    },
    "handlers": {
        "mailer": {
            "command": "\/opt\/sensu-plugins\/handlers\/notification\/mailer.rb -j mailer",
            "type": "pipe",
            "severities": [
                "ok",
                "critical",
                "warning"
            ]
        }
    }
}
```

## Your Environment
* Sensu version used: 0.26.5
* Operating System: Host: ubuntu 14.04, container image: ubuntu 16.04

**Comment by portertech** [comment] 2017-04-07 20:38
We will investigate this early next week :+1:

**Comment by portertech** [comment] 2017-06-14 23:16
We were unable to reproduce the error. Sensu spec tests were also unable to reproduce the error, see https://github.com/sensu/sensu/pull/1688 

You can use `sensu-server --print_config -c /etc/sensu/config.json -d /etc/sensu/conf.d` to print out your configuration to ensure another configuration file isn't overriding or removing the mailer handler severities.

**Comment by portertech** [comment] 2017-06-15 19:59
Closing this issue, as we are unable to reproduce. Please create a new issue if there is further developments 👍

**Closed by portertech** 2017-06-15 19:59 UTC
Labels: Bug, in progress
