### ISSUE TITLE
API died when Uchiwa queried it

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu#1116] opened 2015-11-24 13:14 UTC
Has an issue today whereby Uchiwa made an API call and the api died. Here's the log message:

```
{"timestamp":"2015-11-24T04:55:32.541357-0800","level":"info","message":"GET /clients","remote_address":"172.16.21.73","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/clients?limit=1000&offset=177149000","request_body":""}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:19:in `load': Yajl::ParseError (MultiJson::ParseError)
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json.rb:119:in `load'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/api/process.rb:378:in `block (5 levels) in <class:Process>'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `dispatch_response'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:434:in `process_cmd'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:408:in `receive_data'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/api/process.rb:24:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-api:10:in `<top (required)>'
    from /opt/sensu/bin/sensu-api:23:in `load'
    from /opt/sensu/bin/sensu-api:23:in `<main>'
```

Not sure if this is a sensu-api or an uchiwa thing, so opening it here

**Comment by jaxxstorm** [comment] 2015-11-24 13:50
This is constantly crashing now :(

```
{"timestamp":"2015-11-24T05:48:34.364227-0800","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:19:in `load': Yajl::ParseError (MultiJson::ParseError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json.rb:119:in `load'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/api/process.rb:378:in `block (5 levels) in <class:Process>'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `dispatch_response'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:434:in `process_cmd'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:408:in `receive_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/api/process.rb:24:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-api:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-api:23:in `load'
	from /opt/sensu/bin/sensu-api:23:in `<main>'
```

**Comment by palourde** [comment] 2015-11-24 15:45
@jaxxstorm How many clients do you have on this Sensu API? Also, did you just upgraded your Uchiwa version?

**Comment by jaxxstorm** [comment] 2015-12-01 10:50
Approx 3000 clients.

I have recently updated uchiwa, yes. It's been a lot more stable since I deleted some old stashes, so I'm wondering if this was stale redis data

**Comment by portertech** [comment] 2015-12-04 23:43
We should add a rspec test for the API /clients endpoint, using a crazy pagination offset.

**Comment by calebhailey** [comment] 2016-04-07 16:57
It sounds like the original issue here was resolved, though it may be valuable to add some new tests to avoid future regressions. Should we close this, or leave it open until we add the tests? 

/cc @portertech

**Comment by portertech** [comment] 2017-02-22 17:25
Much of Sensu has changed since this issue was opened. I have tested the original failure conditions with the rewritten API, no failure :+1: (just returns an empty client array, which is correct).

**Closed by portertech** 2017-02-22 17:25 UTC
Labels: Bug
