### ISSUE TITLE
connection errors spam sensu-client.log

### ISSUE THREAD

**Issue by Debilski** [sensu/sensu#1801] opened 2017-12-28 13:22 UTC
Sometimes (probably due to unstable network) sensu-client.log contains Gigabytes of

    {"timestamp":"xxxxx",
     "level":"error",
     "message":"transport connection error",
     "reason":"unable to resolve hostname",
     "host":"monitoring",
     "error":"getaddrinfo: Name or service not known"}

## Expected Behavior
sensu-client.log should not fill the hard drive.

## Current Behavior
hard drive fills

## Possible Solution

Only log the transport connection error once. Or initiate log rotation.

## Your Environment
* Sensu version used: 1.2.0
* Operating System and version (e.g. Debian 8):

**Comment by runningman84** [comment] 2018-01-02 16:44
Maybe sensu core could use the retry gem to have a better retry handling like this:
https://github.com/troyready/sensu-transport-snssqs-ng/commit/e575c859a211bda24a14b9665a7f538032e05aa0
For snssqs this problem seems to be solved...

**Comment by amdprophet** [comment] 2018-01-03 21:12
Duplicate of https://github.com/sensu/sensu/issues/1798.

**Closed by amdprophet** 2018-01-03 21:12 UTC
