### ISSUE TITLE
Windows client unable to load json configs, log shows unexpected character at line 1, column 1

### ISSUE THREAD

**Issue by AirCombat** [sensu/sensu#1232] opened 2016-04-14 23:21 UTC
```
{
  "timestamp": "2016-04-14T23:05:45.043371+0100",
  "level": "warn",
  "message": "config file must be valid json",
  "file": "C:/opt/sensu/conf.d/client.json",
  "error": "unexpected character at line 1, column 1 [parse.c:652]"
}
```

I get this error on all json files.

Using a pretty straight forward json file copied from a linux server, I have been unable to get the most recent version of the MSI client to start because of this error.

Example json file:

```
{
    "client": {
        "name": "Server1",
        "address": "1.1.1.1",
        "subscriptions": [ "none" ]
    }
}
```

You may be able to replicate the issue using my full install script:
http://pastebin.com/GgQsNcAX

EOL symbols:
http://i.stack.imgur.com/aeHfu.png

**Comment by kobbe** [comment] 2016-04-16 19:29
Have you tried unix EOL symbols insted of windows EOL?

**Comment by ransoni** [comment] 2016-04-16 20:27
This might be caused by wrong encoding.
Check that your config file is UTF-8 encoded, and is not UTF-8-BOM.
I had UTF-8-BOM encoded config files first, and they failed to load.

**Comment by calebhailey** [comment] 2016-04-21 18:04
Tagging this for review w/ 0.24. We added BOM detection/removal last year (in [version 0.18][1]), but I wonder if we introduced a regression with new JSON changes in 0.23. 

In the interim, ensuring that your configs are not UTF-8 encoded should resolve the issue. 

Thanks for the report. #monitoringlove 

[1]: https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0180---2015-05-05

**Comment by wbrodie** [comment] 2016-04-21 18:40
IIRC:
Powershell encoding is UCS-2 LE BOM
Command Prompt encoding is UTF-8

Should be able to use both to create files.

Changing the files to UTF-8 fixes this.

I recommend having some Windows centric functional testing / end-to-end for the MSI builds. - Powershell bootstrap scripts, Powershell DSC etc...

The irony is that the specifications for ecma/JSON were originally UCS-2 / UTF-16

**Comment by calebhailey** [comment] 2016-06-13 16:14
The 0.25 release is going to hit today with fewer features than originally anticipated & primarily only some internal improvements. Moving this issue to 0.26.

**Comment by calebhailey** [comment] 2017-03-20 05:32
I believe this issue was resolved, but we forgot to circle back and close it. I'm going to close this due to inactivity. Please feel free to create a new issue if anyone is still seeing this behavior. :v:

**Comment by portertech** [comment] 2017-03-22 19:33
We may need to document that Windows Sensu configuration JSON files must be UTF-8. Not convinced we can "fix" or strip various BOMs and force encoding.

**Comment by portertech** [comment] 2017-03-27 16:11
Windows configuration encoding limitations have been documented. Closing this issue.

**Closed by portertech** 2017-03-27 16:11 UTC
Labels: Documentation, ready
