### ISSUE TITLE
Sensu API never starts listening when transport never successfully connects

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1215] opened 2016-04-08 18:21 UTC
When the Sensu API is started up, the debug message: `connecting to transport` prints, and if the connection fails for a more subtle reason than `Connection refused`, Sensu constantly attempts to reconnect every 2 seconds, without the `Transport.connect()` ever yielding a `connection` object.

On startup when the `transport` connection fails, this prevents the API from ever listening.

This problem occurs with Sensu 0.23 from the Ubuntu repository, but in Sensu 0.22, the API successfully listens and tells Uchiwa that the transport is not connected, which is the correct behaviour since my transport is currently not working for some configuration reason that's my fault.

The log messages for this are also pretty terrible, as Sensu API prints nothing at the default log level. It should print the following with `@logger.{info,error}()` by default:

- Connecting to transport
- Connection failed (including the reason), reconnecting to transport

Also, the API should still come up and serve requests even when the `transport` fails to connect, so clients like Uchiwa can see the reason why the API is in a bad state.

See my notes on these commits for a possible solution:

- [sensu/sensu/commit/7c39541a](https://github.com/sensu/sensu/commit/7c39541a#diff-2a7cdd2fd11ac77dc3f35be73e06b7d0R188)
- [sensu/sensu-transport/commit/ddafe4f](https://github.com/sensu/sensu-transport/commit/ddafe4fcee6e10281233623c013732aea2576568#diff-080a905f5ab39312d2a80c541ccb1583R125)
- [sensu-transport/commit/7bbf2437](https://github.com/nhooey/sensu-transport/commit/7bbf2437#diff-080a905f5ab39312d2a80c541ccb1583R184)

**Comment by calebhailey** [comment] 2016-04-13 17:47
@nhooey hi there! :wave: 

Thank you for submitting this issue. The behavior you're describing isn't a bug as much as the result of [changes to the Sensu Transport that defer processing until a connection is successfully establish][1]. I'm giving this issue the documentation label so we can clarify this change in behavior in the documentation. 

Having said that, we do agree that &ndash; because the API is used to provide visibility into Sensu's health via dashboards such as Uchiwa &ndash; the API should still respond to requests while it waits for transport connection to be established, so we'll label this as a feature as well, and work on getting it scheduled ASAP. 

/cc @amdprophet 

[1]: https://sensuapp.org/docs/latest/changelog

**Comment by amdprophet** [comment] 2016-04-13 17:56
Hi @nhooey,

I'm planning on making a change to the Sensu API so that it returns an error code (perhaps 500?) until the transport and redis connection objects have been created. This should allow for Uchiwa to determine that the API is not yet available which is expected behaviour.

**Comment by nhooey** [comment] 2016-04-13 18:07
Hey @amdprophet, as long as the verbose details of the error are included in the message, and repeated by Uchiwa to the user, that should be fine.

Something like this:
```
Sensu API failed due to the following problems:
- Failed to connect to RabbitMQ at <RMQ_HOST>:<RMQ_PORT>: "Connection refused"
- Failed to connect to Redis at <REDIS_HOST>:<REDIS_PORT>: "Connection timed out"
```

**Comment by calebhailey** [comment] 2016-04-26 15:43
Presumptively tagging this for the 0.24 release.

**Comment by portertech** [comment] 2016-05-30 19:11
Merged https://github.com/sensu/sensu/pull/1298 which closes this :+1:

**Closed by portertech** 2016-05-30 19:11 UTC
Labels: Documentation, Feature, in progress
