### ISSUE TITLE
Sensu-api and checks

### ISSUE THREAD

**Issue by altvnk** [sensu/sensu#1138] opened 2015-12-15 10:07 UTC
To get know about existing checks sensu-api needs to load them from config dir. I'm wondering why this is needed? Why to not register checks from server somewhere in redis so api can safely read them.

I'm working on sensu setup on microservices, so all of sensu components are decoupled. I was really surprised that my checks is not showing until i've putted them into sensu-api container. Suggestions?

**Comment by portertech** [comment] 2016-01-05 19:59
@altvnk this is by design, what's on disk is the truth. The API /checks endpoint was only ever intended to provide information/options for POST /request.

**Comment by maticmeznar** [comment] 2016-01-28 10:43
I just hit the same bug. If this is by design, then IMO it should be explained somewhere that server and api daemons need have access to the same checks and that both need to be restarted when making changes to checks. A possible solution would be to add a topic in documentation titled "Running in container/docker" and describe common caveats like this.

**Comment by calebhailey** [comment] 2016-04-07 00:22
Created an issue for this in sensu-docs and tagged it for release with the 0.23 documentation.

**Comment by portertech** [comment] 2017-03-20 19:56
Closing this issue, however, https://github.com/sensu/sensu-docs/issues/353 is still open an queued up to be addressed.

**Closed by portertech** 2017-03-20 19:56 UTC
Labels: Documentation, Wrong Repo
