### ISSUE TITLE
Is it possible to increase the history in event data?

### ISSUE THREAD

**Issue by pietervogelaar** [sensu/sensu#1781] opened 2017-11-08 09:38 UTC
At the moment the history array in event data contains the last 20 check exit codes. I my handler filter I do some logic based on the history to reduce noise to Slack.

```
  # The fifteenth occurrence after state change (role:windows 60th) or resolve after at least 15 times critical
  # Noise can be reduced for certain checks even more by setting the check.occurrences attribute larger than 15
  state_change_with_occurrences_critical:
    negate: false
    attributes:
      occurrences: "eval: (':::client.role:::' != 'windows' && value == :::check.occurrences|15:::) || (':::client.role:::' == 'windows' && value == :::check.occurrences|60:::) || ':::action:::' == 'resolve'"
      check:
        history: "eval: (value.last == '0' && value[-16...-1].uniq.length == 1 && value[-16...-1].uniq[0] == '2') || (value.last == '2' && value[-15...-1].uniq.length == 1 && value[-15...-1].uniq[0] == '2')"
```

But I like to have more than 20 history entries, let's say 100. Is that possible?

**Comment by pietervogelaar** [comment] 2017-11-08 09:44
What I want to accomplish is improve the ` ':::action:::' == 'resolve'` part. To receive only a resolve message after the error/warning was during at least X time.

**Comment by cwjohnston** [comment] 2017-11-08 21:26
Hi @pietervogelaar.  Sensu stores the last 21 check result statuses to enable the flap detection algorithm and the number of entries is not currently configurable.

It seems like you might be trying to use filters to implement your own flap detection. Have you had a look at the [check flap threshold attributes](https://sensuapp.org/docs/latest/reference/checks.html#check-attributes)  that control the flap detection algorithm? These settings might help you make appropriate adjustments without needing to change Sensu's history registry, as you can use filters to evaluate whether or not the event action is 'flapping' .

I'd also recommend configure your handler(s) to use the [built-in `occurrences` filter](https://github.com/sensu-extensions/sensu-extensions-occurrences). This filter ensures that your configured check occurrences have been met before allowing the event to be handled. Because Sensu will AND together the filters defined on a handler, there shouldn't be a need to reproduce the occurrence logic in your own filters.

**Comment by pietervogelaar** [comment] 2017-11-09 07:58
Hi @cwjohnston,

Thanks for your suggestion about flapping. However I don't think that is sufficient. On Slack I only want to receive events that require human attention. So even for a check that never flapped, but is for the first time critical, I only want to get notified if it's critical for a certain amount of time or X occurences.

**Comment by cwjohnston** [comment] 2018-08-02 20:04
>  I only want to get notified if it's critical for a certain amount of time or X occurences.

This is the purpose of the built-in occurrences filter. Please see our [built-in filter reference documentation](https://docs.sensu.io/sensu-core/latest/reference/filters/#built-in-filters-occurrences) for details and examples.

Closing this issue for now as I believe the `occurrences` filter provides sufficient coverage for this use case.

**Closed by cwjohnston** 2018-08-02 20:04 UTC
