### ISSUE TITLE
Incorrect logs and behavior whith wrong rabbit credentials

### ISSUE THREAD

**Issue by fxpester** [sensu/sensu#1550] opened 2017-02-09 15:22 UTC
## Expected Behavior
When sensu can`t auth at rabbit vhost, it should report error in logs

## Current Behavior
Even with debug enabled only "connecting to redis" and "connecting to transport" records appears,  also sensu starts to reconnect to redis which is misleading to investigate redis first

## Possible Solution
Catch and log auth errors

## Steps to Reproduce (for bugs)

1. follow guidlines till rabbit activation
2. in rabbit instead of vhost '/sensu' set it to 'sensu'
3. enable debug 
4. check logs

## Context
1 day of debugging possible haproxy or redis-sentinel or redis replication errors.

## Your Environment

* Sensu version used: 0.26.5
* Active Sensu extensions (e.g. WizardVan 0.1.0):
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 14.04
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ 3.6.5

**Comment by cwjohnston** [comment] 2017-02-09 16:01
Hi @fxpester, thanks for opening this issue. We've recently released version 0.27 which includes changes to sensu-transport intended to better surface RabbitMQ connection errors in Sensu's logs (see https://github.com/sensu/sensu-transport/issues/30 and https://github.com/sensu/sensu-transport/issues/34). 

Due to AMQP implementation details, Sensu experiences authentication failures as premature termination of the TCP connection. As a result, Sensu can't definitively indicate which aspect of the username/password/vhost combination is incorrect, but, as of 0.27, it will log `"possible authentication failure. wrong credentials?"` when the when TCP connection is closed before authentication finishes.

Closing as duplicate of https://github.com/sensu/sensu-transport/issues/30

**Closed by cwjohnston** 2017-02-09 16:01 UTC
