### ISSUE TITLE
Sensu doesn't send 'resolve' action to any handlers after exiting flapping in resolved state

### ISSUE THREAD

**Issue by raffraffraff** [sensu/sensu#1565] opened 2017-02-17 12:07 UTC
On any of our alerts that have a tendency to flap, we regularly have to go to our pager and manually resolve them. This behavior has been an annoyance since I've been using Sensu (v 0.12).

There are a few reasons why I'm creating an issue now:
- We have completely rebuilt our sensu environment on the latest version, using the Redis transport
- We have completely disabled sensu-handler occurrences filtering
- We only use the sensu core 'occurrences' filter [extension]
- We have written a simple log file handler that handles 'flapping'. It shows the initial failure, there is then a gap (occurrence filtering) and then 19 consecutive 'status:0' updates with the state 'flapping' ...and nothing more.
- We cannot see any resolve actions in the sensu-server.log

Sample output from the log file handler:
```
2017-02-17 10:32:59 +0000  host1/check_load, team: team1, status:2, occurrences:5, interval:60, refresh:, action:create
2017-02-17 10:41:59 +0000  host1/check_load, team: team1, status:0, occurrences:5, interval:60, refresh:, action:flapping
2017-02-17 10:42:59 +0000  host1/check_load, team: team1, status:0, occurrences:6, interval:60, refresh:, action:flapping
2017-02-17 10:43:59 +0000  host1/check_load, team: team1, status:0, occurrences:7, interval:60, refresh:, action:flapping
2017-02-17 10:44:59 +0000  host1/check_load, team: team1, status:0, occurrences:8, interval:60, refresh:, action:flapping
2017-02-17 10:45:59 +0000  host1/check_load, team: team1, status:0, occurrences:9, interval:60, refresh:, action:flapping
2017-02-17 10:46:59 +0000  host1/check_load, team: team1, status:0, occurrences:10, interval:60, refresh:, action:flapping
2017-02-17 10:47:59 +0000  host1/check_load, team: team1, status:0, occurrences:11, interval:60, refresh:, action:flapping
2017-02-17 10:48:59 +0000  host1/check_load, team: team1, status:0, occurrences:12, interval:60, refresh:, action:flapping
2017-02-17 10:49:59 +0000  host1/check_load, team: team1, status:0, occurrences:13, interval:60, refresh:, action:flapping
2017-02-17 10:50:59 +0000  host1/check_load, team: team1, status:0, occurrences:14, interval:60, refresh:, action:flapping
2017-02-17 10:51:59 +0000  host1/check_load, team: team1, status:0, occurrences:15, interval:60, refresh:, action:flapping
2017-02-17 10:52:59 +0000  host1/check_load, team: team1, status:0, occurrences:16, interval:60, refresh:, action:flapping
2017-02-17 10:53:59 +0000  host1/check_load, team: team1, status:0, occurrences:17, interval:60, refresh:, action:flapping
2017-02-17 10:54:59 +0000  host1/check_load, team: team1, status:0, occurrences:18, interval:60, refresh:, action:flapping
2017-02-17 10:55:59 +0000  host1/check_load, team: team1, status:0, occurrences:19, interval:60, refresh:, action:flapping
```

## Expected Behavior

When a check exits flapping mode on a resolve, it should send the 'resolve' action to handlers. This is not as important when it exits flapping on a failure, as they'll eventually get around the occurrences filter and fire again.

## Current Behavior

When flapping ends on a 'status: 0', no action is taken.

## Steps to Reproduce (for bugs)

1. Enabling flap handling in a handler
2. Send sensu a check with alternating status to enable flapping mode
3. Send 19 consecutive successful checks to exit flapping mode

## Context

If a check exits flapping mode with status:0, and sensu fails to send a 'resolve' action to the handler, the check remains in a failed state. This is dangerous because it means that a future failure will not notify oncall, as the pager already thinks that the check has been failing.

## Your Environment

* Sensu version used: 0.27 (but also affected previous versions; 0.26-5, 0.25, and others)
* Active Sensu extensions (e.g. WizardVan 0.1.0): occurrences filter
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): Redis ruby-2.3.1-r0 transport (but this also affected our previous RabbitMQ transports, on multiple versions)

**Comment by portertech** [comment] 2017-02-22 05:59
@raffraffraff please provide the check definition for "check_load".

**Comment by raffraffraff** [comment] 2017-02-22 12:54
```
    "check_load": {
      "command": "check_load $args",
      "interval": 60,
      "handlers": [ "victorops" ],
      "occurrences": 5,
      "subscribers": [ ],
      "standalone": true,
      "high_flap_threshold": 25,
      "low_flap_threshold": 5
    }
```

We don't explicitly add 'refresh', but Sensu's default should cover that.

**Comment by portertech** [comment] 2017-03-22 05:34
@raffraffraff I am unable to reproduce this issue, #1638 confirms that handlers are executed following a flapping to resolve action transition. Are you still experiencing this? Have you tried debug logging to gain more insight?

**Comment by portertech** [comment] 2017-03-22 19:25
Moving to 1.1 until we hear back from @raffraffraff, not going to block 0.29.

**Comment by johanek** [comment] 2017-03-28 14:02
I've experienced this when testing flapping checks. The resolve action isn't handled, with the message `handler does not handle event severity`.

The log:
```
{"timestamp":"2017-03-28T13:43:30.585548+0000","level":"info","message":"handler does not handle event severity","handler":{"command":"handler-pagerduty.rb","type":"pipe","mutator":"xmlapi","filters":["occur
rences"],"severities":["ok","warning","critical"],"handle_flapping":true,"name":"pagerduty"},"event":{"client":{,"name":"redacted","address":"unknown","subscrip
tions":[],"keepalives":false,"version":"0.26.5","timestamp":1490708609},"check":{"name":"johan-test-incident","status":0,"output":"The check failed but this is only a test","handler":"pagerduty","source":"redacted","enable_deprecated_filtering":false,"refresh":86400,"pager_team":"engineering","priority":"PRI-2","description":"This is
a test incident for demoing pagerduty","occurrences":5,"low_flap_threshold":10,"high_flap_threshold":30,"executed":1490708610,"issued":1490708610,"type":"standard","origin":"redacted
","history":["0","2","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],"total_state_change":8},"occurrences":18,"occurrences_watermark":18,"action":"resolve","timestamp":1490708610
,"id":"b1de84f2-1211-487e-a4ac-7c8db71a6361","last_state_change":1490708610,"last_ok":1490708610,"silenced":false,"silenced_by":[]}}
```

This looks to be caused by this: https://github.com/sensu/sensu/blob/master/lib/sensu/server/filter.rb#L52 - As the previous result in the history is a 0, `handle_severity?` returns `false`.

**Comment by raffraffraff** [comment] 2017-03-28 16:19
Apologies for the long delay in replying. I've been upgrading all of ours servers and clients to 0.28.4, which has better log output for filtered events.  I'm going to try to do more testing at the weekend.

`handler does not handle event severity` is the same message I have been getting.

**Comment by portertech** [comment] 2017-03-28 16:33
@raffraffraff your handler uses `severities: ["critical"]` etc.

**Comment by portertech** [comment] 2017-03-28 16:34
@johanek oh, thank you, will investigate later today :+1:

**Comment by portertech** [comment] 2017-06-09 22:46
This was fixed in https://github.com/sensu/sensu/pull/1683 1.0.0 will include these changes 👍

**Closed by portertech** 2017-06-09 22:46 UTC
Labels: Bug, in progress
