### ISSUE TITLE
Sensu handler always fires even with filters and stashed items

### ISSUE THREAD

**Issue by FartParty** [sensu/sensu#1032] opened 2015-08-28 06:46 UTC
I have a sensu handler that always executes, even when filters are defined and/or when a stash item is created for that check.

The handler and filters are both on the sensu server only, the client does not have the filters.  The handler is a standalone program written in Go.

Sensu version: 0.18.1
Server: Ubuntu 14.04

Filter definition:
```json
{
  "filters": {
    "dumb_repeat_alerts": {
      "attributes": {
        "client": {
          "environment": "somenv"
        },
        "check": {
          "name": "dumb_program_running"
        }
      }
    }
  }
}
```

Handler definition:
```json
{
  "handlers": {
    "foo": {
      "type": "pipe",
      "command": "sensu-handler-foo",
      "severities": [
        "ok",
        "warning",
        "critical"
      ],
      "filters": [
        "dumb_repeat_alerts"
      ]
    }
  }
}
```

Additionally in the server log, when I change the config file, I see what appears to be a parsing error for the filter:

```json
{"timestamp":"2015-08-27T22:57:11.359334-0700","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/filters/dumb_repeat_alerts.json","changes":{"filters":{"dumb_repeat_alerts":[null,{"attributes":{"client":{"environment":"somenv"},"check":{"name":"dumb_program_running"}}}]}}}
```

**Comment by portertech** [comment] 2015-10-19 21:48
Hi @FartParty, your defined filter `dumb_repeat_alerts` will let any event with the defined attributes pass through (not negated). As for event silencing with stashes, your event handler written in golang must query the Sensu API to check for their existence (its up to the handler).

**Comment by fessyfoo** [comment] 2015-11-19 14:31
for example note this handler with embeded filtering on silenced stashes.   https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-handler.rb#L144

( is this issue really a bug?  or should it be closed as works as designed? )

**Comment by calebhailey** [comment] 2016-04-09 16:32
Looks like this should have been closed, so I'm going to go ahead and close it. Please feel free to create a new issue if this matter is not resolved. #monitoringlove

**Closed by calebhailey** 2016-04-09 16:32 UTC
Labels: Bug
