### ISSUE TITLE
Sensu Handler not working properly with severities

### ISSUE THREAD

**Issue by arunssasidhar** [sensu/sensu#1827] opened 2018-03-12 17:16 UTC
## Expected Behavior
I am trying to separate the alerts "critical" and "warning" to send to 2 different Slack channels using "handler-slack.rb". I set "slack" as default handler. 
I am expecting "warning alert" in "warning slack channel". And only "critical alert" in "critical slack channel".

Here is my config :::

`# cat default_handlers.json 
{
  "handlers": {
    "default": {
      "type": "set",
      "handlers": [
        "slack-event",
	"slack-alert"
      ]
    },
.................
..........`

`# cat slack_handler.json 
{
   "handlers":{
      "slack-event":{
         "type":"pipe",
         "command":"/usr/bin/handler-slack.rb -j slack-event",
         "severites":[
            "warning"
         ],
	 "filter": "recurrence"
      },
      "slack-alert":{
         "type":"pipe",
         "command":"/usr/bin/handler-slack.rb -j slack-alert",
         "severities":[
            "critical",
            "unknown"
         ],
	 "filter": "recurrence"
      }
   },
   "slack-event":{
      "webhook_url":"https://hooks.slack.com/services/T6*****************************************ld",
      "template":""
   },
   "slack-alert":{
      "webhook_url":"https://hooks.slack.com/services/T6*************************************3O",
      "template":""
   }
}
`
## Current Behavior
 "critical alert" is coming in "critical slack channel" but "warning alert" and "critical alert" are coming in "warning slack channel". 

## Your Environment
Sensu Server Version : 1.0.0

**Comment by bartlamboo** [comment] 2018-03-13 08:13
If I had to guess it was because of the typo you have in your config.

{
	"handlers": {
		"slack-event": {
			"type": "pipe",
			"command": "/usr/bin/handler-slack.rb -j slack-event",
			**"severites": ["warning"],**
			"filter": "recurrence"
		},
		"slack-alert": {
			"type": "pipe",
			"command": "/usr/bin/handler-slack.rb -j slack-alert",
			"severities": ["critical", "unknown"],
			"filter": "recurrence"
		}
	},
	"slack-event": {
		"webhook_url": "https://hooks.slack.com/services/T6*****************************************ld",
		"template": ""
	},
	"slack-alert": {
		"webhook_url": "https://hooks.slack.com/services/T6*************************************3O",
		"template": ""
	}
}

**Comment by arunssasidhar** [comment] 2018-03-13 08:48
What is the typo here? I even tried without square brackets as shown below ::

`{
   "handlers":{
      "slack-alert":{
         "type":"pipe",
         "command":"/usr/bin/handler-slack.rb -j slack-alert",
         "severities":[
            "critical",
            "unknown"
         ],
         "filters":[
            "recurrence",
            "only_crtical_unknown"
         ]
      },
      "slack-event":{
         "type":"pipe",
         "command":"/usr/bin/handler-slack.rb -j slack-event",
         "severites":"warning",
         "filters":[
            "recurrence",
            "only_warning"
         ]
      }      
   },
   "slack-alert":{
      "webhook_url":"https://hooks.slack.com/services/T6********************************************
3O",
      "template":""
  },
   "slack-event":{
      "webhook_url":"https://hooks.slack.com/services/T6****************ld",
      "template":""
   }
}`

**Comment by mcbsdEU** [comment] 2018-03-13 09:05
Man...
"severities":[ "critical", "unknown" ]
"severites":"warning"

**Comment by arunssasidhar** [comment] 2018-03-13 11:21
oh okay, I corrected it. But still the same behaviour ::::

`{
   "handlers":{
      "slack-event":{
         "type":"pipe",
         "command":"/usr/bin/handler-slack.rb -j slack-event",
         "severities":[
            "warning"
         ],
	 "filter": "recurrence"
      },
      "slack-alert":{
         "type":"pipe",
         "command":"/usr/bin/handler-slack.rb -j slack-alert",
         "severities":[
            "critical",
            "unknown"
         ],
	 "filter": "recurrence"
      }
   },
   "slack-event":{
      "webhook_url":"https://hooks.slack.com/services/T6************************************ld",
      "template":""
   },
   "slack-alert":{
      "webhook_url":"https://hooks.slack.com/services/T6L*****************************************3O",
      "template":""
   }
}
`

**Comment by cwjohnston** [comment] 2018-03-14 20:35
Hi @arunssasidhar, we feel pretty confident that this is a configuration issue and not a bug in Sensu's `severities` handling. I can see that you have raised this issue in our Community Slack and I've made a comment on that existing thread with some suggestions. 

I'm going to close this issue for now, but please feel free to contact us on Slack for further assistance.

**Closed by cwjohnston** 2018-03-14 20:35 UTC
