### ISSUE TITLE
Typo in logs "severites" (should be "severities")

### ISSUE THREAD

**Issue by mutorsound** [sensu/sensu#1806] opened 2018-01-23 20:34 UTC
This log is slightly munged by Splunk/Logstash but the keyname "severites" is a misspelling:

{"timestamp":"2018-01-23T19:58:17.276394+0000","level":"info","message":"handler output","handler":{"type":"pipe","command":"/opt/sensu/embedded/bin/handler-slack-multichannel.rb","**severites**":["critical","warning"],"name":"slack"},"output":["using check default channels: #xxx\ntarget channels: #xxx\nrequest: #<Net::HTTP::Post:XXX>\nresponse: #<Net::HTTPOK:XXX>\n"],"@timestamp":"2018-01-23T19:58:18.098Z","path":"/var/log/sensu/sensu-server.log","type":"sensu","tags":["service","sensu"],"zone":"XXX","env":"XXX","instance_id":"XXX","svtype":"sensu-server","index_env":"XXX","hostname":"XXX","ipaddr":"X"}

Couldn't find the spelling in the github project, but page https://github.com/sensu/sensu-ansible/blob/3ca090822804fa8720d016b539eaf88992c9e99c/docs/deploy_plugins.md has an example that also refers to this spelling.

(found in Sensu Enterprise 0.25.7 running on Amazon Linux but the problem seems to exist elsewhere in Sensu core)

**Comment by cwjohnston** [comment] 2018-02-14 21:08
Hi @mutorsound, thanks for raising this issue. I have looked through code in relevant Sensu repositories and haven't found a matching misspelling. 

It seems to me that the typo may originate from the "slack" handler definition in your Sensu configuration. Handler definitions are included in log messages like the one you've provided, so any misspellings or additional data present in the handler definition will be part of the log message by design.

Since I can't find any indication that this is actually a misspelling in Sensu, I'm going to close this issue for now. Please feel free to respond with any further evidence, at which point we can consider reopening the issue.

**Closed by cwjohnston** 2018-02-14 21:08 UTC
