### ISSUE TITLE
Sensu conf.d/*.json files are being overwritten by an empty config.json hash

### ISSUE THREAD

**Issue by pgporada** [sensu/sensu#1544] opened 2017-02-02 17:30 UTC
## Expected Behavior
An empty configuration hash should not stomp changes in `/etc/sensu/conf.d/*.json` files.

## Current Behavior
Initial deploy
```
-----> Running bats test suite
 ✓ Install helper packages for testing
 ✓ Sensu is installed
 ✓ Sensu-server is running
 ✓ Sensu-server is enabled
 ✓ Sensu-api is running
 ✓ Sensu-api is enabled
 ✓ Sensu-client is running
 ✓ Sensu-client is enabled
 ✓ Validate the compiled Sensu configuration
 ✓ We can authenticate to the sensu api
 ✓ Sensu /info endpoint shows transport is connected
 ✓ Sensu /info endpoint shows redis is connected
 ✓ Ensure uchiwa is running
 ✓ Ensure uchiwa is enabled
 ✓ Uchiwa health is ok
 ✓ Uchiwa can connect to sensu-api
```
The `/etc/sensu/conf.d/api.json` will be deployed with the following content
```
{
  "api": {
    "host": "127.0.0.1",
    "port": 4567,
    "user": "sensu",
    "password": "somepassword",
    "bind": "127.0.0.1"
  }
}
```

Wait a minute or 2

```
-----> Running bats test suite
 ✓ Install helper packages for testing
 ✓ Sensu is installed
 ✓ Sensu-server is running
 ✓ Sensu-server is enabled
 ✓ Sensu-api is running
 ✓ Sensu-api is enabled
 ✓ Sensu-client is running
 ✓ Sensu-client is enabled
 ✓ Validate the compiled Sensu configuration
 ✓ We can authenticate to the sensu api
 ✓ Sensu /info endpoint shows transport is connected
 ✓ Sensu /info endpoint shows redis is connected
 ✓ Ensure uchiwa is running
 ✓ Ensure uchiwa is enabled
 ✓ Uchiwa health is ok
 ✗ Uchiwa can connect to sensu-api
          (in test file /tmp/verifier/suites/bats/02_uchiwa.bats, line 30)
            `[[ "$output" =~ "ok" ]]' failed
          Connection error. Is the Sensu API running?
```

The `/etc/sensu/conf.d/api.json` file will now look like this
```
{
  "api": {
    "host": "127.0.0.1",
    "port": 4567,
    "user": "sensu",
    "password": "somepassword",
    "bind": "localhost"
  }
}
```

I will then see these logs in `/var/log/sensu/sensu-api.log`
```
{"timestamp":"2017-02-02T17:11:30.459031+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/api.json"}
{"timestamp":"2017-02-02T17:11:30.459105+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/api.json","changes":{"api":[null,{"host":"127.0.0.1","port":4567,"user":"sensu","password":"REDACTED","bind":"localhost"}]}}
{"timestamp":"2017-02-02T17:11:30.671168+0000","level":"info","message":"api listening","protocol":"http","bind":"localhost","port":4567}
```

## Possible Solution
Don't allow an empty configuration hash to stomp changes in `/etc/sensu/conf.d/*.json`

## Steps to Reproduce (for bugs)
/etc/sensu/config.json
```
{
}
```

/etc/sensu/conf.d/api.json
```
{
  "api": {
    "host": "127.0.0.1",
    "port": 4567,
    "user": "sensu",
    "password": "somepassword",
    "bind": "127.0.0.1"
  }
}
```

## Context
Our `uchiwa` deployment stops communicating with the `sensu-api` because localhost on this vagrant box binds to ipv6 first.

## Your Environment
* Sensu version used: `sensu-0.26.5-2.x86_64`
* Active Sensu extensions: none
* Operating System and version: CentOS 7.2
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): `rabbitmq-server-3.3.5-28.el7.noarch` and `erlang 03.18.el7.x86_64`
* Redis: `redis-2.8.19-2.el7.x86_64`

**Comment by pgporada** [comment] 2017-02-02 17:51
I should note that this only happens when using `"bind": "127.0.0.1` and not `"bind": "0.0.0.0"`.

**Comment by cwjohnston** [comment] 2017-02-03 18:30
Hi @pgporada, thanks for opening this issue. I've tried to reproduce the behavior you're describing but I haven't been successful. 

In my testing I've created `/etc/sensu/config.json` with an empty JSON document:

```
root@default-ubuntu-1604:~# cat /etc/sensu/config.json
{}
```

I've also created `/etc/sensu/conf.d/more_config.json` with API bind and host attributes set to 127.0.0.1, as shown in your example:

```
root@default-ubuntu-1604:~# cat /etc/sensu/conf.d/more_config.json
{
  "transport": {
    "reconnect_on_error": true,
    "name": "redis"
  },
  "api": {
    "host": "127.0.0.1",
    "bind": "127.0.0.1",
    "port": 4567
  }
}
```

With this configuration in place, I use the `--print_config` flag for sensu-client to provide me with details on the order in which the config is loaded, and the final configuration after deep merging is complete:

```
root@default-ubuntu-1604:~# sudo -u sensu /opt/sensu/bin/sensu-client -c /etc/sensu/config.json -d /etc/sensu/conf.d --print_config
{"timestamp":"2017-02-03T18:09:20.786112+0000","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
{"timestamp":"2017-02-03T18:09:20.786870+0000","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2017-02-03T18:09:20.787439+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/more_config.json"}
{"timestamp":"2017-02-03T18:09:20.788417+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/more_config.json","changes":{"transport":{"name":["rabbitmq","redis"]},"api":[null,{"host":"127.0.0.1","bind":"127.0.0.1","port":4567}]}}
{"timestamp":"2017-02-03T18:09:20.788903+0000","level":"warn","message":"applied sensu client overrides","client":{"name":"default-ubuntu-1604","address":"10.0.2.15","subscriptions":["client:default-ubuntu-1604"]}}
{"timestamp":"2017-02-03T18:09:20.789868+0000","level":"warn","message":"outputting compiled configuration and exiting"}
{
  "client":{
    "name":"default-ubuntu-1604",
    "address":"10.0.2.15",
    "subscriptions":[
      "client:default-ubuntu-1604"
    ]
  },
  "sensu":{
    "spawn":{
      "limit":12
    }
  },
  "transport":{
    "name":"redis",
    "reconnect_on_error":true
  },
  "checks":{},
  "filters":{},
  "mutators":{},
  "handlers":{},
  "extensions":{},
  "api":{
    "host":"127.0.0.1",
    "bind":"127.0.0.1",
    "port":4567
  }
}
```

From my perspective this is working as intended, and the empty JSON document in `/etc/sensu/config.json` has no observable effect.

Your suggestion to "Wait a minute or 2" makes me wonder if some other part of your automation is overwriting the Sensu configuration on disk.

For what its worth, changing the value of the `bind` attribute from "0.0.0.0" to "127.0.0.1" may also require a change to Uchiwa's configuration. Can you check your Uchiwa config (usually `/etc/sensu/dashboard.json` or under `/etc/sensu/dashboard.d`) to ensure it's using the same "127.0.0.1" address ?

**Comment by pgporada** [comment] 2017-02-04 21:36
Here is my `/etc/sensu/uchiwa.json`
```
 {
   "sensu": [{
        "name": "GLVagrant",
        "user": "sensu",
        "pass": "somepassword",
        "host": "127.0.0.1",
        "port": 4567,
        "ssl": false,
        "insecure": true,
        "timeout": 60
   }],
   "uchiwa": {
     "host": "127.0.0.1",
     "port": 3000,
     "loglevel": "info",
     "interval": 5,
     "users": [
                {
            "username" : "phil",
            "password": "phil",
            "readonly": false
                    }
    ]}
}
```

**Comment by amdprophet** [comment] 2017-02-17 22:00
Sensu currently treats any configuration in `/etc/sensu` as read-only and is unable to modify its configuration during runtime. As we were unable to reproduce this issue I am going to close this issue.

As for why `localhost` doesn't work but `127.0.0.1` does, `localhost` can sometimes resolve to an IPv6 address on dual-stack systems which can cause the API to only listen on IPv6. The resolution for this is to listen on an IPv4 only address (e.g. `127.0.0.1`) or the dual-stack equivalent of `0.0.0.0` which is `::` or sometimes `[::]`.

**Closed by amdprophet** 2017-02-17 22:00 UTC
Labels: in progress
