### ISSUE TITLE
Missing 'Date' entry in APT repository

### ISSUE THREAD

**Issue by ydkn** [sensu/sensu#1135] opened 2015-12-11 09:25 UTC
Newer versions of APT require a *Date* entry in the Release file.

Currently this happens on Debian testing:

```
W: Failed to fetch http://repositories.sensuapp.org/apt/dists/sensu/Release  Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/repositories.sensuapp.org_apt_dists_sensu_Release
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Salamek** [comment] 2015-12-16 18:57
I'm having same issue here

```
W: Failed to fetch http://repositories.sensuapp.org/apt/dists/sensu/Release  Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/repositories.sensuapp.org_apt_dists_sensu_Release
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by tata2000** [comment] 2015-12-17 11:53
Same here. Please add `Date` entry to `http://repositories.sensuapp.org/apt/dists/sensu/Release` file.


    W: Failed to fetch http://repos.sensuapp.org/apt/dists/sensu/Release  Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/repos.sensuapp.org_apt_dists_sensu_Release
    E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by Salamek** [comment] 2015-12-17 19:29
Oh and this is happening only when using debian unstable (sid), debian stable is OK

**Comment by portertech** [comment] 2016-01-05 20:06
Interesting, I will check on freight, see if there's an update.

**Comment by rs-mrichmond** [comment] 2016-03-03 19:34
Currently this is also an issue with Ubuntu 16.04 (Beta)

Also reported in #1151

**Comment by jaredledvina** [comment] 2016-03-09 07:37
@portertech - It looks like this PR https://github.com/freight-team/freight/pull/1/files might have added support to include the ``Date`` feild to freight. Thoughts?

**Comment by rosenfeld** [comment] 2016-03-11 17:46
I had a problem with my previous Sensu server and I'm having to set up a new server and trying to do so on Debian sid is not possible due to this issue. Is there any estimate for when this will be fixed?

**Comment by calebhailey** [comment] 2016-04-07 00:27
I inadvertently labeled this as "wrong repo" thinking this was an issue w/ sensu-build, but that's not the case. 

We're tagging this for resolution along with the 0.24 release as this will impact Ubuntu 16.04 users.

**Comment by jaredledvina** [comment] 2016-04-07 02:53
@calebhailey - Yes! Thank you!

**Comment by Artanicus** [comment] 2016-04-21 16:55
Ubuntu 16.04 is out, what's the status on this? Any workarounds in the meanwhile?

**Comment by rs-mrichmond** [comment] 2016-04-21 22:42
My current workaround is manually grabbing and installing to .deb files.

**Comment by sulemanhasib43** [comment] 2016-04-27 08:09
After the release of 16.04 the issue is still the same. The only solution is what @rs-mrichmond stated.

**Comment by amdprophet** [comment] 2016-04-27 16:53
This should be fixed now. Please make sure that you're using `repositories.sensuapp.org` and not `repos.sensuapp.org` in your APT sources.

**Comment by portertech** [comment] 2016-04-27 16:54
APT https://sensuapp.org/docs/latest/sensu-on-ubuntu-debian#install-sensu-core-repository

YUM https://sensuapp.org/docs/latest/sensu-on-rhel-centos

**Comment by jaredledvina** [comment] 2016-04-28 07:50
Looks good on my end! Thanks!
```
root@balerion <~>
# apt --version
apt 1.2.10 (amd64)
Supported modules:
*Ver: Standard .deb
*Pkg:  Debian dpkg interface (Priority 30)
 Pkg:  Debian APT solver interface (Priority -1000)
 S.L: 'deb' Debian binary tree
 S.L: 'deb-src' Debian source tree
 Idx: Debian Source Index
 Idx: Debian Package Index
 Idx: Debian Translation Index
 Idx: Debian dpkg status file
 Idx: Debian deb file
 Idx: Debian dsc file
 Idx: Debian control file
 Idx: EDSP scenario file
```

```
root@server1 <~>
# apt-get update
Hit:1 http://security.debian.org testing/updates InRelease
Ign:2 http://repositories.sensuapp.org/apt sensu InRelease
Hit:3 http://repositories.sensuapp.org/apt sensu Release
Hit:4 http://mirrors.ocf.berkeley.edu/debian testing InRelease
Hit:5 http://mirrors.kernel.org/debian testing-updates InRelease
Reading package lists... Done
```

```
root@server1 <~>
# apt-get install sensu
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be upgraded:
  sensu
1 upgraded, 0 newly installed, 0 to remove and 85 not upgraded.
Need to get 32.3 MB of archives.
After this operation, 70.7 kB disk space will be freed.
Get:1 http://repositories.sensuapp.org/apt sensu/main amd64 sensu amd64 0.23.2-1 [32.3 MB]
Fetched 32.3 MB in 30s (1,046 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 173637 files and directories currently installed.)
Preparing to unpack .../sensu_0.23.2-1_amd64.deb ...
Unpacking sensu (0.23.2-1) over (0.23.0-3) ...
Processing triggers for systemd (229-4) ...
Setting up sensu (0.23.2-1) ...
```

**Comment by portertech** [comment] 2016-04-28 19:04
Closing this one, as the active (non deprecated) repositories have been updated :+1:

**Closed by portertech** 2016-04-28 19:04 UTC
Labels: Bug

**Comment by peterlavelle** [comment] 2016-10-10 10:38
Hi,

Having an issue installing the sensu repo. I changed the repository source from  repos.sensuapp.org to repositories.sensuapp.org but the sensu package is flagged as un-authenticated when I attempt to install it. 

Output from apt-key list is below

```
pub   2048R/7580C77F 2012-05-02
uid                  Sonian Inc (Sensu signing key) <chefs@sonian.net>

pub   2048R/EB9C94BB 2015-08-31
uid                  Freight <support@hw-ops.com>
```

I'm using http://repositories.sensuapp.org/apt/keyring.gpg  as the source URL for the key.
