### ISSUE TITLE
filter occurrences prior to creating events

### ISSUE THREAD

**Issue by fessyfoo** [sensu/sensu#1620] opened 2017-03-15 00:21 UTC
Feature request,  events_registry (and possibly results api) take into account occurrence filtering. 

## Proposed Behavior

some ability to apply occurrence filtering before updating the event registry.  

more complex consideration,  someone replicating the state of sensu into a dashboarding system based off of event_bridges would need some indicator of wether the event was in a  triggered state or not. 

## Current Behavior

Uchiwa and other dashboards based of the events api endpoint, show certain events as failing, even though with occurrence filtering taken into account, the handlers haven't been called to notify anyone and one could consider it not yet failing. 

## Context

I think it may be worth thinking of occurrence filtering as a uniq and special thing compared to other potential custom filters.  It's  effectively labeling  the state of an event as active.  

In our environment people have complained about this,  while managers see big prominent dashboards and ask why they are failing.  service owners have to say technically it's not a failing check.

 In Nagios' a check being retried,  is displayed as green / passing with a failure count until it passes the failure threshold.   so UI's and Notifications are in sync.  

###  a nuanced consideration
since occurrences filtering is now implementable as an extension,  it implies variations are possible in the semantics and Indeed Yelp and ourselves who followed  are using [a variant](https://github.com/Yelp/sensu_handlers/blob/62eafd0/files/base.rb#L210-L257) that's based of of different control keywords in the check.      so whatever mechanism solves the events_registry issue should be generic enough to keep the plugable occurrence filtering in tact.

**Comment by mcbsdEU** [comment] 2017-03-15 18:38
I would be also interested in something like this.
Not only occurrences filtering, but also filtering in general.
Etc. check dependencies - it is designed that only root cause event is passed to handler but if there are many dependencies, each of them gets own event and you end up with red dashboard. How to deal with these events afterwards, etc. to resolve them? On one side it is good to see all events to have complete real time picture but on other side if it could be somehow separated...
We forward events to 3rd party ticketing interface however to see Uchiwa full of events which have no actual impact as itself makes bit itchy feeling.

**Comment by portertech** [comment] 2017-03-20 02:03
Filtering before the event registry does not make much sense as the registry represents the up-to-date state of events indicating a failure state. This up-to-date state is used by much of Sensu's internal logic. An event can have one or more handlers, each that have their own mutator & filter(s) applied, multiple pipelines, some of which do not filter by the event occurrences.

Occurrences filtering is used for alerting/notification purposes, not for indicating a failing state, as the check execution has already done so. Uchiwa already supports hiding events that are under their check occurrence threshold, perhaps further improvements could be made here.

Closing this issue due the the reasons above.

**Closed by portertech** 2017-03-20 02:03 UTC
