### ISSUE TITLE
Source and non-unique check names

### ISSUE THREAD

**Issue by ohaddal** [sensu/sensu#939] opened 2015-05-06 10:45 UTC
Hi,

When using the source attribute in checks, it appears you need unique check names for them to be picked up by Sensu. 

Example: Having 10 HP switches with unique source-attributes but all running a check called "check_hp", only one switch will be registered. Changing to "check_hp1", "check_hp2" and so on, all will register as expected.

OS: Debian Wheezy
Sensu: 0.18
Uchiwa: 0.8.1

Not seeing anything obvious in the logs, services have been restarted and redis flushed.

**Comment by portertech** [comment] 2015-05-06 18:04
@ohaddal Thank you for the issue. I am unable to reproduce, example:

```
portertech@d2o:~/projects/sensu/sensu (master=)$ echo '{"source": "switch-y", "name": "test", "output": "testing", "status": 2}' | nc localhost 3030 
ok

portertech@d2o:~/projects/sensu/sensu (master=)$ echo '{"source": "switch-x", "name": "test", "output": "testing", "status": 2}' | nc localhost 3030
ok

portertech@d2o:~/projects/sensu/sensu (master=)$ echo '{"source": "switch-z", "name": "test", "output": "testing", "status": 2}' | nc localhost 3030
ok

portertech@d2o:~/projects/sensu/sensu (master=)$ curl -i http://foo:bar@localhost:4567/clients                                                       
HTTP/1.1 200 OK
Content-Type: application/json;charset=utf-8
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Content-Length: 478
Connection: keep-alive
Server: thin 1.5.0 codename Knife

[{"name":"switch-z","address":"unknown","subscriptions":[],"keepalives":false},{"name":"switch-y","address":"unknown","subscriptions":[],"keepalives":false},{"name":"switch-x","address":"unknown","subscriptions":[],"keepalives":false},{"name":"i-424242","address":"127.0.0.1","subscriptions":["test"],"keepalive":{"thresholds":{"warning":10}},"version":"0.18.0","nested":{"attribute":true},"service":{"password":"REDACTED"},"empty":{},"localhost":"fail","timestamp":1430934967}]

portertech@d2o:~/projects/sensu/sensu (master=)$ curl -i http://foo:bar@localhost:4567/events
HTTP/1.1 200 OK
Content-Type: application/json;charset=utf-8
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Content-Length: 2793
Connection: keep-alive
Server: thin 1.5.0 codename Knife

[{"id":"8dedad88-6983-4049-b642-cbadd0aea6a2","client":{"name":"switch-z","address":"unknown","subscriptions":[],"keepalives":false},"check":{"source":"switch-z","name":"test","output":"testing","status":2,"issued":1430935375,"history":["2"],"total_state_change":0},"occurrences":1,"action":"create"},{"id":"01f3f6d3-db1e-414b-9718-93a7e7d7b1b6","client":{"name":"switch-y","address":"unknown","subscriptions":[],"keepalives":false},"check":{"source":"switch-y","name":"test","output":"testing","status":2,"issued":1430935369,"history":["2"],"total_state_change":0},"occurrences":1,"action":"create"},{"id":"22fb3cb0-00bc-43b3-a91b-01eac97ef589","client":{"name":"switch-x","address":"unknown","subscriptions":[],"keepalives":false},"check":{"source":"switch-x","name":"test","output":"testing","status":2,"issued":1430935372,"history":["2"],"total_state_change":0},"occurrences":1,"action":"create"},{"id":"3c4ad666-858a-48e0-b636-0567374bf4ce","client":{"name":"i-424242","address":"127.0.0.1","subscriptions":["test"],"keepalive":{"thresholds":{"warning":10}},"version":"0.18.0","nested":{"attribute":true},"service":{"password":"REDACTED"},"empty":{},"localhost":"fail","timestamp":1430935370},"check":{"thresholds":{"warning":10,"critical":180},"handler":"keepalive","name":"keepalive","issued":1430935380,"executed":1430935380,"output":"No keepalive sent from client for 10 seconds (>=10)","status":1,"history":["1"],"total_state_change":0},"occurrences":1,"action":"create"},{"id":"4afbcf7d-1298-492e-8a64-eb8b85db529f","client":{"name":"i-424242","address":"127.0.0.1","subscriptions":["test"],"keepalive":{"thresholds":{"warning":10}},"version":"0.18.0","nested":{"attribute":true},"service":{"password":"REDACTED"},"empty":{},"localhost":"fail","timestamp":1430935370},"check":{"command":"echo -n foobar && exit 1","standalone":true,"interval":1,"name":"standalone","issued":1430935390,"executed":1430935390,"duration":0.004,"output":"foobar","status":1,"history":["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1"],"total_state_change":0},"occurrences":40,"action":"create"},{"id":"4be4a9fb-ff37-47f2-a66d-e2f006a95776","client":{"name":"i-424242","address":"127.0.0.1","subscriptions":["test"],"keepalive":{"thresholds":{"warning":10}},"version":"0.18.0","nested":{"attribute":true},"service":{"password":"REDACTED"},"empty":{},"localhost":"fail","timestamp":1430935390},"check":{"command":"echo -n :::name::: :::nested.attribute::: && exit 2","subscribers":["test"],"interval":1,"name":"tokens","issued":1430935391,"executed":1430935391,"duration":0.005,"output":"i-424242 true","status":2,"history":["2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2"],"total_state_change":0},"occurrences":41,"action":"create"}]
```

**Comment by portertech** [comment] 2015-05-06 18:47
Oh, I see, you're attempting to have a check definition load for a client. Because Sensu configuration is composed of deep merged configuration files, the check name must be unique.

**Comment by portertech** [comment] 2015-05-06 18:49
I will be sure to mention this in the 0.18 documentation. You can expect the 0.18 documentation to be available by EOD PST.

**Comment by aidanjl** [comment] 2015-05-28 04:59
I just hit this issue too.
I have a check named "check_apache_processes". First server has critical limit of 150 but my second server has limit of 400. If I use the same name the new server keeps alerting for 150.
These servers are in different environments so I will prepend the env to the check name.

**Comment by portertech** [comment] 2015-06-18 21:54
@aidanjl all Sensu servers must have the same configuration, they elect a leader for issuing check requests.

**Comment by calebhailey** [comment] 2016-04-09 19:14
Closing due to inactivity. Please feel free to create a new issue if this matter is not resolved. #monitoringlove

**Closed by calebhailey** 2016-04-09 19:14 UTC
