### ISSUE TITLE
Subdue checks

### ISSUE THREAD

**Issue by kaushiksriram100** [sensu/sensu#1280] opened 2016-05-25 00:21 UTC
Not sure if I am understand this wrong, But I setup a subdue between 11AM PT AND 11:59 PT for a check. What I see is that check hasn't run since 11:00 am and it's now 6 hours. This is what I see in the logs. 

And the subdue for keepalive is showing some mixed results, I am still testing that. 

``` json
{
  "timestamp": "2016-05-24T17:13:58.087530-0700",
  "level": "info",
  "message": "check request was subdued",
  "check": {
    "handlers": [
      "generic_email_notify",
      "logstash",
      "remediator"
    ],
    "command": "check-procs.rb -p crond -C 1",
    "interval": 60,
    "subscribers": [
      "monitoring-servers"
    ],
    "trigger_on": [
      "monitoring-servers"
    ],
    "team": "test@example.com",
    "subdue": {
      "at": "publisher",
      "days": [
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday"
      ],
      "begin": "11AM PT",
      "end": "11:59AM PT"
    },
    "runbook": "test",
    "remediation": {
      "remediate_cron_1": {
        "occurrences": [
          "2-3"
        ],
        "severities": [
          2
        ]
      }
    },
    "name": "proc_cron"
  }
}
```

**Comment by calebhailey** [comment] 2016-07-15 20:22
@kaushiksriram100 your configuration looks correct, so the check should have been executed again after the subdue period. Unfortunately, we're not able to reproduce this behavior - can you provide any additional details or configuration?

**Comment by raffraffraff** [comment] 2017-02-17 11:16
This is an old issue and I'm not sure which versions were used: but I also had issues getting subdue to work when I added a timezone. My config also looked fine (based on this one). So I ended up creating a filter using eval time to suppress warnings during specific hours, and assigned the filter to the handler for our pager. [It's more important to suppress warnings from our pager than than to suppress all handlers at the check level, since we only have one handler that wakes engineers]

```
{
  "filters": {
    "subdue_warnings": {
      "negate": true,
      "attributes": {
        "check": {
          "status": "1"
        },
        "timestamp": "eval:  Time.now.utc.hour.between?(7,15)"
      }
    }
  }
}
```

**Comment by portertech** [comment] 2017-03-20 03:58
Sensu check `subdue` and filter `when` had significant changes/improvements as of Sensu 0.26 (https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0260---2016-09-06), pretty much a rewrite. 

I am closing this issue as it is no longer relevant to recent releases, please feel free to create a new issue if you are still experiencing issues with subdue with Sensu >= 0.26.

**Closed by portertech** 2017-03-20 03:58 UTC
