### ISSUE TITLE
Segmentation fault on CentOS 6.9

### ISSUE THREAD

**Issue by rwky** [sensu/sensu#1652] opened 2017-04-10 11:03 UTC
When running check-disk-usage.rb I get a segmentation fault intermittently, this has only happened since upgrading to CentOS 6.9 from 6.8.

## Expected Behavior
No segmentation faults

## Current Behavior
```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem.rb:315: [BUG] Segmentation fault at 0x00000000000000
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0006 p:---- s:0026 e:000025 CFUNC  :getmntent
c:0005 p:0581 s:0022 e:000021 METHOD /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem.rb:315
c:0004 p:0014 s:0012 e:000011 METHOD /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-2.0.1/bin/check-disk-usage.rb:121
c:0003 p:0008 s:0009 e:000008 METHOD /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-2.0.1/bin/check-disk-usage.rb:206
c:0002 p:0039 s:0006 e:000005 BLOCK  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:58 [FINISH]
c:0001 p:0000 s:0002 E:001030 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-2.0.1/bin/check-disk-usage.rb:206:in `run'
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-disk-checks-2.0.1/bin/check-disk-usage.rb:121:in `fs_mounts'
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem.rb:315:in `mounts'
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem.rb:315:in `getmntent'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f2b8ae7cceb RBP: 0x0000000000000000 RSP: 0x00007fffdfb945f0
 RAX: 0x0000000000000000 RBX: 0x0000000001e51250 RCX: 0x0000000000001000
 RDX: 0x0000000001e51250 RDI: 0x0000000000000000 RSI: 0x00007f2b8b12b060
  R8: 0x00007f2b8b128188  R9: 0x0000000000000001 R10: 0x0000000000001000
 R11: 0x0000000000000206 R12: 0x00007f2b8b12b060 R13: 0x0000000000001000
 R14: 0x0000000001dbaf68 R15: 0x00007f2b8c30fed0 EFL: 0x0000000000010206

-- C level backtrace information -------------------------------------------
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bdfd91d]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bdfdd5a]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bc81b9c]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bd60d2d]
/lib64/libpthread.so.0 [0x7f2b8ba047e0]
/lib64/libc.so.6(__getmntent_r+0x1b) [0x7f2b8ae7cceb]
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so(ffi_call_unix64+0x4c) [0x7f2b844ec264] /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/ext/ffi_c/libffi/src/x86/ffi64.c:633
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so(ffi_call+0x3e3) [0x7f2b844ebcc0] /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/ext/ffi_c/libffi/src/x86/ffi64.c:486
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so(rbffi_CallFunction+0x3fc) [0x7f2b844eaa7f]
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so [0x7f2b844defeb]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bde1258]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bde1d96]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bde1f95]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bde2d49]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bde340a]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bde35e5]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bde7340]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bdf9135]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bdf7558]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bdf7414]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bdf75bb]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bdf785a]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bdf7987]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bc8f1f5]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bc87196]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bc87339]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bc87440]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bc878b3]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bc87b5e]
/opt/sensu/embedded/lib/libruby.so.2.3 [0x7f2b8bc88099]
/opt/sensu/embedded/bin/ruby(main+0x4f) [0x4008a7]

-- Other runtime information -----------------------------------------------

* Loaded script: /opt/sensu/embedded/bin/check-disk-usage.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/enc/encdb.so
    5 /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/enc/trans/transdb.so
    6 /opt/sensu/embedded/lib/ruby/2.3.0/unicode_normalize.rb
    7 /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/rbconfig.rb
    8 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/compatibility.rb
    9 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/defaults.rb
   10 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/deprecate.rb
   11 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/errors.rb
   12 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/version.rb
   13 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb
   14 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/platform.rb
   15 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb
   16 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb
   17 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/util/list.rb
   18 /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/stringio.so
   19 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb
   20 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/exceptions.rb
   21 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_gem.rb
   22 /opt/sensu/embedded/lib/ruby/2.3.0/monitor.rb
   23 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb
   24 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb
   25 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb
   26 /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb
   27 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/version.rb
   28 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb
   29 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/levenshtein.rb
   30 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/jaro_winkler.rb
   31 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkable.rb
   32 /opt/sensu/embedded/lib/ruby/2.3.0/delegate.rb
   33 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   34 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   35 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   36 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   37 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/null_checker.rb
   38 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/formatter.rb
   39 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean.rb
   40 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin.rb
   41 /opt/sensu/embedded/lib/ruby/2.3.0/optparse.rb
   42 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb
   43 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb
   44 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/check/cli.rb
   45 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem/constants.rb
   46 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so
   47 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/platform.rb
   48 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/types.rb
   49 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/library.rb
   50 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/errno.rb
   51 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/pointer.rb
   52 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/memorypointer.rb
   53 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/struct_layout_builder.rb
   54 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/struct.rb
   55 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/union.rb
   56 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/managedstruct.rb
   57 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/callback.rb
   58 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/io.rb
   59 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/autopointer.rb
   60 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/variadic.rb
   61 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/enum.rb
   62 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/ffi.rb
   63 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi.rb
   64 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem/structs.rb
   65 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem/functions.rb
   66 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem.rb
   67 /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/filesystem.rb

* Process memory map:

00400000-00401000 r-xp 00000000 b6:89d11 142609                          /opt/sensu/embedded/bin/ruby
00600000-00601000 rw-p 00000000 b6:89d11 142609                          /opt/sensu/embedded/bin/ruby
0192c000-01e73000 rw-p 00000000 00:00 0                                  [heap]
7f2b840e4000-7f2b842ba000 r--s 00000000 b6:89d11 4044                    /lib64/libc-2.12.so
7f2b842ba000-7f2b842d0000 r-xp 00000000 b6:89d11 23523                   /lib64/libgcc_s-4.4.7-20120601.so.1
7f2b842d0000-7f2b844cf000 ---p 00016000 b6:89d11 23523                   /lib64/libgcc_s-4.4.7-20120601.so.1
7f2b844cf000-7f2b844d0000 rw-p 00015000 b6:89d11 23523                   /lib64/libgcc_s-4.4.7-20120601.so.1
7f2b844d0000-7f2b844f4000 r-xp 00000000 b6:89d11 149502                  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so
7f2b844f4000-7f2b846f3000 ---p 00024000 b6:89d11 149502                  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so
7f2b846f3000-7f2b846f5000 rw-p 00023000 b6:89d11 149502                  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so
7f2b846f5000-7f2b846fd000 r-xp 00000000 b6:89d11 143675                  /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/stringio.so
7f2b846fd000-7f2b848fc000 ---p 00008000 b6:89d11 143675                  /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/stringio.so
7f2b848fc000-7f2b848fd000 rw-p 00007000 b6:89d11 143675                  /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/stringio.so
7f2b848fd000-7f2b848ff000 r-xp 00000000 b6:89d11 143641                  /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/enc/trans/transdb.so
7f2b848ff000-7f2b84aff000 ---p 00002000 b6:89d11 143641                  /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/enc/trans/transdb.so
7f2b84aff000-7f2b84b00000 rw-p 00002000 b6:89d11 143641                  /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/enc/trans/transdb.so
7f2b84b00000-7f2b84b02000 r-xp 00000000 b6:89d11 143599                  /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/enc/encdb.so
7f2b84b02000-7f2b84d01000 ---p 00002000 b6:89d11 143599                  /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/enc/encdb.so
7f2b84d01000-7f2b84d02000 rw-p 00001000 b6:89d11 143599                  /opt/sensu/embedded/lib/ruby/2.3.0/x86_64-linux/enc/encdb.so
7f2b84d02000-7f2b8ab97000 r--p 00000000 b6:89d11 276182                  /usr/lib/locale/locale-archive
7f2b8ab97000-7f2b8ab99000 r-xp 00000000 b6:89d11 3940                    /lib64/libfreebl3.so
7f2b8ab99000-7f2b8ad98000 ---p 00002000 b6:89d11 3940                    /lib64/libfreebl3.so
7f2b8ad98000-7f2b8ad99000 r--p 00001000 b6:89d11 3940                    /lib64/libfreebl3.so
7f2b8ad99000-7f2b8ad9a000 rw-p 00002000 b6:89d11 3940                    /lib64/libfreebl3.so
7f2b8ad9a000-7f2b8af24000 r-xp 00000000 b6:89d11 4044                    /lib64/libc-2.12.so
7f2b8af24000-7f2b8b124000 ---p 0018a000 b6:89d11 4044                    /lib64/libc-2.12.so
7f2b8b124000-7f2b8b128000 r--p 0018a000 b6:89d11 4044                    /lib64/libc-2.12.so
7f2b8b128000-7f2b8b12a000 rw-p 0018e000 b6:89d11 4044                    /lib64/libc-2.12.so
7f2b8b12a000-7f2b8b12e000 rw-p 00000000 00:00 0 
7f2b8b12e000-7f2b8b1b1000 r-xp 00000000 b6:89d11 15128                   /lib64/libm-2.12.so
7f2b8b1b1000-7f2b8b3b0000 ---p 00083000 b6:89d11 15128                   /lib64/libm-2.12.so
7f2b8b3b0000-7f2b8b3b1000 r--p 00082000 b6:89d11 15128                   /lib64/libm-2.12.so
7f2b8b3b1000-7f2b8b3b2000 rw-p 00083000 b6:89d11 15128                   /lib64/libm-2.12.so
7f2b8b3b2000-7f2b8b3b9000 r-xp 00000000 b6:89d11 4149                    /lib64/libcrypt-2.12.so
7f2b8b3b9000-7f2b8b5b9000 ---p 00007000 b6:89d11 4149                    /lib64/libcrypt-2.12.so
7f2b8b5b9000-7f2b8b5ba000 r--p 00007000 b6:89d11 4149                    /lib64/libcrypt-2.12.so
7f2b8b5ba000-7f2b8b5bb000 rw-p 00008000 b6:89d11 4149                    /lib64/libcrypt-2.12.so
7f2b8b5bb000-7f2b8b5e9000 rw-p 00000000 00:00 0 
7f2b8b5e9000-7f2b8b5eb000 r-xp 00000000 b6:89d11 15127                   /lib64/libdl-2.12.so
7f2b8b5eb000-7f2b8b7eb000 ---p 00002000 b6:89d11 15127                   /lib64/libdl-2.12.so
7f2b8b7eb000-7f2b8b7ec000 r--p 00002000 b6:89d11 15127                   /lib64/libdl-2.12.so
7f2b8b7ec000-7f2b8b7ed000 rw-p 00003000 b6:89d11 15127                   /lib64/libdl-2.12.so
7f2b8b7ed000-7f2b8b7f4000 r-xp 00000000 b6:89d11 15134                   /lib64/librt-2.12.so
7f2b8b7f4000-7f2b8b9f3000 ---p 00007000 b6:89d11 15134                   /lib64/librt-2.12.so
7f2b8b9f3000-7f2b8b9f4000 r--p 00006000 b6:89d11 15134                   /lib64/librt-2.12.so
7f2b8b9f4000-7f2b8b9f5000 rw-p 00007000 b6:89d11 15134                   /lib64/librt-2.12.so
7f2b8b9f5000-7f2b8ba0c000 r-xp 00000000 b6:89d11 3921                    /lib64/libpthread-2.12.so
7f2b8ba0c000-7f2b8bc0c000 ---p 00017000 b6:89d11 3921                    /lib64/libpthread-2.12.so
7f2b8bc0c000-7f2b8bc0d000 r--p 00017000 b6:89d11 3921                    /lib64/libpthread-2.12.so
7f2b8bc0d000-7f2b8bc0e000 rw-p 00018000 b6:89d11 3921                    /lib64/libpthread-2.12.so
7f2b8bc0e000-7f2b8bc12000 rw-p 00000000 00:00 0 
7f2b8bc12000-7f2b8bee6000 r-xp 00000000 b6:89d11 142743                  /opt/sensu/embedded/lib/libruby.so.2.3.0
7f2b8bee6000-7f2b8c0e5000 ---p 002d4000 b6:89d11 142743                  /opt/sensu/embedded/lib/libruby.so.2.3.0
7f2b8c0e5000-7f2b8c0ee000 rw-p 002d3000 b6:89d11 142743                  /opt/sensu/embedded/lib/libruby.so.2.3.0
7f2b8c0ee000-7f2b8c100000 rw-p 00000000 00:00 0 
7f2b8c100000-7f2b8c120000 r-xp 00000000 b6:89d11 10929                   /lib64/ld-2.12.so
7f2b8c1b3000-7f2b8c1b4000 rw-p 00000000 00:00 0 
7f2b8c1b4000-7f2b8c1bb000 r--s 00000000 b6:89d11 262716                  /usr/lib64/gconv/gconv-modules.cache
7f2b8c1bb000-7f2b8c1ed000 r--s 00000000 b6:89d11 149502                  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so
7f2b8c1ed000-7f2b8c210000 r--s 00000000 b6:89d11 3921                    /lib64/libpthread-2.12.so
7f2b8c210000-7f2b8c317000 rw-p 00000000 00:00 0 
7f2b8c317000-7f2b8c319000 r--s 00000000 b6:89d11 142609                  /opt/sensu/embedded/bin/ruby
7f2b8c319000-7f2b8c31a000 r-xp 00000000 00:00 0 
7f2b8c31a000-7f2b8c31b000 ---p 00000000 00:00 0 
7f2b8c31b000-7f2b8c31f000 rw-p 00000000 00:00 0 
7f2b8c31f000-7f2b8c321000 r--p 0001f000 b6:89d11 10929                   /lib64/ld-2.12.so
7f2b8c321000-7f2b8c322000 rw-p 00021000 b6:89d11 10929                   /lib64/ld-2.12.so
7f2b8c322000-7f2b8c323000 rw-p 00000000 00:00 0 
7fffdf199000-7fffdfb98000 rw-p 00000000 00:00 0                          [stack]
7fffdfbe3000-7fffdfbe5000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

```
## Possible Solution
Perhaps something needs recompiling and packaging for 6.9?

## Steps to Reproduce (for bugs)
1. Install sensu on a CentOS 6.9 box
2. Set a regular check for check-disk-usage.rb
3. Wait 24 hours an error should happen

## Your Environment
* Sensu version used: sensu.x86_64 1:0.26.5-2 from the sensu repo
* Operating System and version: CentOS 6.9

**Comment by cwjohnston** [comment] 2017-04-10 15:19
This appears to be a duplicate of https://github.com/sensu-plugins/sensu-plugins-disk-checks/issues/65, so I'm going to close this issue in favor of that one. 

We'll work on getting https://github.com/sensu-plugins/sensu-plugins-disk-checks/pull/66 merged and released to address the segfault.

**Closed by cwjohnston** 2017-04-10 15:19 UTC
