### ISSUE TITLE
Sensu Server is not working, restart does not work

### ISSUE THREAD

**Issue by kabakakao** [sensu/sensu#1413] opened 2016-08-16 11:42 UTC
The Sensu Server isn't working. The Clients send the data to the server, but he doesn't recognize them.
But there are no keepalive Error Messages.
A Try to restart the server ends in a timeout

Try to restart:

```
/etc/init.d/sensu-server restart
configuration is valid
 * Stopping sensu-server
 * Timed out waiting for sensu-server to stop
```

Excerpt of server-log:

```
{"timestamp":"2016-08-16T10:52:42.721104+0000","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-08-16T10:52:42.721230+0000","level":"warn","message":"stopping"}
{"timestamp":"2016-08-16T10:52:42.721317+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-08-16T10:52:42.721561+0000","level":"warn","message":"resigning as leader"}
{"timestamp":"2016-08-16T10:52:42.721599+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":2,"events":0}}
{"timestamp":"2016-08-16T10:52:57.730058+0000","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-08-16T10:52:57.730183+0000","level":"warn","message":"stopping"}
{"timestamp":"2016-08-16T10:52:57.730219+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-08-16T10:52:57.730371+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":2,"events":0}}
{"timestamp":"2016-08-16T10:53:13.740482+0000","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-08-16T10:53:13.740608+0000","level":"warn","message":"stopping"}
{"timestamp":"2016-08-16T10:53:13.740644+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-08-16T10:53:13.740766+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":2,"events":0}}
{"timestamp":"2016-08-16T10:53:28.750240+0000","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-08-16T10:53:28.750365+0000","level":"warn","message":"stopping"}
{"timestamp":"2016-08-16T10:53:28.750398+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-08-16T10:53:28.750515+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":2,"events":0}}
{"timestamp":"2016-08-16T11:30:06.813612+0000","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-08-16T11:30:06.813718+0000","level":"warn","message":"stopping"}
{"timestamp":"2016-08-16T11:30:06.813751+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-08-16T11:30:06.813864+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":2,"events":0}}
```

strace:

```
/home/ubuntu# strace -p 28489
Process 28489 attached
select(11, [7 9 10], [], [], {0, 380714}) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 93044850}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 93161833}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 93218948}) = 0
select(11, [7 9 10], [], [], {0, 49737}) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 143289156}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 143392469}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 143477307}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 143547709}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 143609675}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 143659261}) = 0
select(11, [7 9 10], [], [], {0, 442269}) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 586599263}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 586720860}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 586777276}) = 0
select(11, [7 9 10], [], [], {0, 6384}) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 593430505}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 593509387}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 593572888}) = 0
select(11, [7 9 10], [], [], {0, 49820}) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 643680988}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 643801988}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 643874839}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 643940620}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 644002249}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322238, 644049465}) = 0
select(11, [7 9 10], [], [], {0, 449460}) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC_RAW, {4322239, 94215137}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322239, 94363336}) = 0
clock_gettime(CLOCK_MONOTONIC_RAW, {4322239, 94419900}) = 0
select(11, [7 9 10], [], [], {0, 49382}) = 0 (Timeout)
```

**Comment by runningman84** [comment] 2016-08-17 19:15
It looks like after some time we cannot stop sensu anymore. It receives the TERM signal according to the logs and stops processing events. But the sensu server process stays alive and does not fully terminate. 

@portertech Is this a known bug?

**Comment by runningman84** [comment] 2016-08-22 14:02
@cwjohnston or @portertech what are these "in_progress" events?

I am thinking about putting something like kill -9 in the sensu init script. But this problem should be better solved in the sensu process...

**Comment by cwjohnston** [comment] 2016-08-23 15:21
Hi @kabakakao @runningman84, can you please provide some additional context? e.g.:

* Sensu version used?
* Operating System and version? (e.g. Ubuntu 14.04)
* Transport and runtime versions? (e.g. RabbitMQ 3.6.2 on Erlang 18.2)
* Which versions of community plugins and/or extensions are in use on the Sensu server (e.g. handlers)?

**Comment by cwjohnston** [comment] 2016-08-23 15:42
@runningman84 Sensu 0.24 added an internal `in_progress` hash for keeping count of work in progress, e.g. number of checks being processed, events being mutated, events being handled, etc. 

The output @kabakakao provided gives us some idea that the sensu-server process is waiting for two check results to be processed before shutting down:

`{"timestamp":"2016-08-16T11:30:06.813864+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":2,"events":0}}`

But we lack context to know what the content of those check results might be, [or at what point they seem to be stuck in processing](https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L571).

**Comment by runningman84** [comment] 2016-08-24 07:57
@cwjohnston the problem happens in all 0.25.x versions right now we use 0.25.7. The problem does not occur on 0.23.x, we haven't used 0.24.x here. We have seen this problem with redis, rabbitmq and snssqs transports. We are using Ubuntu 14.04

The problem even occurs in a small kitchen demo.

We use this cookbook to setup sensu:
https://github.com/runningman84/chef-monitor

I have modified the init script to execute a kill -9 if the normal kill does not work. Here you can see that in 3 out of 5 cases the server did not stop because of in_progress events:
```
grep -n -A 5 TERM sensu-server.log 
60:{"timestamp":"2016-08-23T10:54:43.377518+0000","level":"warn","message":"received signal","signal":"TERM"}
61-{"timestamp":"2016-08-23T10:54:43.377878+0000","level":"warn","message":"stopping"}
62-{"timestamp":"2016-08-23T10:54:43.378281+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
63-{"timestamp":"2016-08-23T10:54:43.378789+0000","level":"warn","message":"resigning as leader"}
64-{"timestamp":"2016-08-23T10:54:43.378983+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":0,"events":0}}
65-{"timestamp":"2016-08-23T10:54:43.880208+0000","level":"warn","message":"stopping reactor"}
--
864:{"timestamp":"2016-08-23T11:50:53.022504+0000","level":"warn","message":"received signal","signal":"TERM"}
865-{"timestamp":"2016-08-23T11:50:53.022636+0000","level":"warn","message":"stopping"}
866-{"timestamp":"2016-08-23T11:50:53.022691+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
867-{"timestamp":"2016-08-23T11:50:53.022830+0000","level":"warn","message":"resigning as leader"}
868-{"timestamp":"2016-08-23T11:50:53.022870+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":1,"events":0}}
869-{"timestamp":"2016-08-23T11:51:02.796952+0000","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
--
2006:{"timestamp":"2016-08-23T13:12:44.052386+0000","level":"warn","message":"received signal","signal":"TERM"}
2007-{"timestamp":"2016-08-23T13:12:44.052620+0000","level":"warn","message":"stopping"}
2008-{"timestamp":"2016-08-23T13:12:44.052697+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
2009-{"timestamp":"2016-08-23T13:12:44.052864+0000","level":"warn","message":"resigning as leader"}
2010-{"timestamp":"2016-08-23T13:12:44.053089+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":1,"events":0}}
2011-{"timestamp":"2016-08-23T13:12:53.641294+0000","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
--
3660:{"timestamp":"2016-08-24T07:34:53.489185+0000","level":"warn","message":"received signal","signal":"TERM"}
3661-{"timestamp":"2016-08-24T07:34:53.489515+0000","level":"warn","message":"stopping"}
3662-{"timestamp":"2016-08-24T07:34:53.489696+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
3663-{"timestamp":"2016-08-24T07:34:53.490218+0000","level":"warn","message":"resigning as leader"}
3664-{"timestamp":"2016-08-24T07:34:53.490373+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":1,"events":0}}
3665-{"timestamp":"2016-08-24T07:35:03.769136+0000","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
--
3848:{"timestamp":"2016-08-24T07:43:36.676217+0000","level":"warn","message":"received signal","signal":"TERM"}
3849-{"timestamp":"2016-08-24T07:43:36.676428+0000","level":"warn","message":"stopping"}
3850-{"timestamp":"2016-08-24T07:43:36.676521+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
3851-{"timestamp":"2016-08-24T07:43:36.676760+0000","level":"warn","message":"resigning as leader"}
3852-{"timestamp":"2016-08-24T07:43:36.676869+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":0,"events":0}}
3853-{"timestamp":"2016-08-24T07:43:37.177480+0000","level":"warn","message":"stopping reactor"}
```
This is the full log
https://gist.github.com/runningman84/e2b4d8d3c1c276490b96361c8f662148

There are no special handlers active, only the debug and deregistration handlers are active...

**Comment by runningman84** [comment] 2016-09-09 18:39
@calebhailey any chance to get this fixed soon?
There is another report of this issue in the user group:
https://groups.google.com/forum/m/#!topic/sensu-users/gcx4FJHcMQI

**Comment by calebhailey** [comment] 2016-09-09 23:24
Tagging this for review w/ the impending 0.26.2 release.

**Comment by skurylo** [comment] 2016-09-20 18:15
I can't definitely say we if saw this in 0.23 and 0.24.  Our internal bug was filed Jun 17th and I'm sure we saw it well before then.  One of our servers show the gem creation times as - 
```
drwxr-xr-x. 4 root root 4.0K Jun  9 21:07 ./ruby/gems/2.3.0/gems/sensu-0.23.3
drwxr-xr-x. 4 root root 4.0K Jun 20 17:43 ./ruby/gems/2.3.0/gems/sensu-0.24.1
drwxr-xr-x. 4 root root 4.0K Jul 27 01:26 ./ruby/gems/2.3.0/gems/sensu-0.25.3
```

Which should correlate with when those versions were in use.  We have have ~8 sensu installations, some of which have multiple sensu-server processes in them.

We have also added a kill -9 to our deployment scripts to work around the problem.

> But we lack context to know what the content of those check results might be, or at what point they seem to be stuck in processing.

If you have a suggestion of how I can debug it further, or a patch to apply to process.rb, to gain that context I'd be happy to try it.  Its been quite easy for me to reproduce in the past, though erratic in how long it takes to happen.  That is, sometimes if I restart after 5 minutes it happens again, sometimes it takes a few hours.

I was thinking about adding some debugging lines every time something is added to in progress, and another when its removed.  Then I can look through to see what was added and never removed.  Thoughts?

**Comment by portertech** [comment] 2016-09-20 18:47
Found the cause https://github.com/sensu/sensu/pull/1455

**Comment by cwjohnston** [comment] 2016-09-20 19:24
@kabakakao we think we've identified the source of the incomplete check result processing as being related to check results with an invalid signature. Possibly related to #1435 and #1452. 

Closed by #1455 which will be released in 0.26.2 shortly.

**Closed by cwjohnston** 2016-09-20 19:24 UTC

**Comment by dcrawkstar** [comment] 2016-09-28 20:51
Still seeing issued using 0.26.3-1
`{"timestamp":"2016-09-28T20:24:07.738290+0000","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-09-28T20:24:07.738549+0000","level":"warn","message":"stopping"}
{"timestamp":"2016-09-28T20:24:07.738657+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-09-28T20:24:07.738822+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":0,"events":3}}`

`[root@d5fbe29b96ba kitchen]# /opt/sensu/bin/sensu-server --version
0.26.3`

**Comment by cwjohnston** [comment] 2016-10-04 16:06
@dcrawkstar we need more detail on this, specifically if you are loading any extensions. Will you please open a new issue, using the template to provide context with regard to your environment and configuration?

**Comment by skurylo** [comment] 2016-10-26 17:02
We're still experiencing this issue.  We're running 0.26.3 and have no extensions on centos 6.

Our deployments now automatically kill -9 the sensu-server process if it can't stop, but going back through our logs, the last 5 deployments over the last three weeks have had to the kill -9.

The logs from a recent one
```
{"timestamp":"2016-10-26T00:08:06.817550+0000","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2016-10-26T00:08:06.820421+0000","level":"warn","message":"stopping"}
{"timestamp":"2016-10-26T00:08:06.820501+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2016-10-26T00:08:06.821092+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":2,"events":1}}
```
In that log snippet above, the sensu installation has three sensu-server processes.  They were all restarted and 2 of 3 failed.

I don't know how to reproduce this, however I can pretty much find it on one of our servers every day.

If you have some debugging steps, I'd be happy to try them

**Comment by johntdyer** [comment] 2017-01-04 17:42
Also seeing the same on 0.25.5

```log
[root@sensu3 ~]# /etc/init.d/sensu-server restart
configuration is valid
Stopping sensu-server{"timestamp":"2017-01-04T17:41:45.420798+0000","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2017-01-04T17:41:45.420977+0000","level":"warn","message":"stopping"}
{"timestamp":"2017-01-04T17:41:45.421045+0000","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2017-01-04T17:41:45.421268+0000","level":"info","message":"completing work in progress","in_progress":{"check_results":0,"events":138}}
```\
