### ISSUE TITLE
Restarting Sensu-Client results in stale checks.

### ISSUE THREAD

**Issue by anherrera** [sensu/sensu#1807] opened 2018-01-26 18:16 UTC
## Expected Behavior
- I make a configuration change (usually via ansible) and restart the sensu-client on a node (typically via ansible, but I've also repro'd the issue using a bash script, ssh one liners with -t flag, and manually ssh'ing in myself and restarting the service.)
- The service restarts and check requests/results keep being pushed/pulled, with new check results being added to the client. 

## Current Behavior
- I make a configuration change and restart sensu-client. 
- Most of the time (I'd say at least 80%) the client gets stuck on "Stopping reactor" and no sign in the log that it started back up or did anything. 
- If I fully stop the sensu-client and wait ~90 seconds, and then start it, about 50% of the time it recovers. 
- The other 50% of the time I have to do stop/90 second wait/start/10 second wait/restart before it finally starts working again.
- This makes managing my 80+ sensu clients via ansible completely untenable.

## Possible Solution
I'm not sure what is causing the issue. Are child processes not being killed? Are sockets/ports not being released on a server stop/restart? 
I tried adding timeouts to all my checks, so far things seem okay, but this is a huge issue and our monitoring basically goes down any time I make config changes, and I have to spend sometimes an entire day manually fixing it by restarting the sensu-client manually on each affected node (I've had 40+ go out on me at a time) until it works again.

## Steps to Reproduce (for bugs)
1. Set up a 2-node HA sensu server setup. 
2. Set up one or more subscriptions with checks. Assign TTL values to all the checks. 
3. Set up the sensu client on several nodes and assign them to these subscriptions. My particular setup has each client running ~10 sub checks and ~2 standalone checks.
4. Let the data populate.
5. Run sensu-client restart however you want. Ansible, ssh, etc. 
6. The checks will go stale and you'll get TTL events in sensu until you go back in and restart the service or stop/start/restart until it works again. I had to manually tail logs to make sure it was actually coming back up. 

## Context
I'm trying to manage 80+ nodes as sensu clients via ansible but if I can't restart the client on any of them without bringing my whole system essentially down (and not paging people) it's a no-go.

## Your Environment

* Sensu version used: 1.2.0, tried downgrading to 1.1.3 to see if that would resolve the issue. It did not.
* Active Sensu extensions (e.g. WizardVan 0.1.0): None
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 14.04 servers and CentOS 6.5/6.8/7.3 and RHEL 6.5/6.8 clients
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ 3.6.2 on Erlang 20

**Comment by anherrera** [comment] 2018-02-15 19:39
{"timestamp":"2018-02-15T09:43:25.039601-0800","level":"warn","message":"received signal","signal":"TERM"}
{"timestamp":"2018-02-15T09:43:25.039787-0800","level":"warn","message":"stopping"}
**{"timestamp":"2018-02-15T09:43:25.040054-0800","level":"info","message":"completing checks in progress","checks_in_progress":[]}**
{"timestamp":"2018-02-15T09:43:25.540817-0800","level":"info","message":"closing client sockets"}
{"timestamp":"2018-02-15T09:43:25.541198-0800","level":"warn","message":"stopping reactor"}
{"timestamp":"2018-02-15T09:47:08.703004-0800","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
{"timestamp":"2018-02-15T09:47:08.703113-0800","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2018-02-15T09:47:08.703144-0800","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks.json"}
{"timestamp":"2018-02-15T09:47:08.703185-0800","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks.json","changes":{"checks":{"check_autotest_nodes":[null,{"interval":60,"command":"/opt/sensu/embedded/bin/fdsjfkldsj-endpoint-check.rb -u 'http://localhost/endpoints/fiodhsiofhds' -i 30 -m 45 -t heartbeat -c 0 -w 0","handlers":["staytus","slack"],"standalone":true}],"check_fdsfdsfds_nodes_mm":[null,{"interval":60,"command":"/opt/sensu/embedded/bin/fdsjfkldsj-endpoint-check.rb -u 'http://localhost/endpoints/fiodhsiofhds' -t maintenance_mode -w 25 -c 25","handlers":["staytus","slack"],"standalone":true}]}}}
{"timestamp":"2018-02-15T09:47:08.703234-0800","level":"warn","message":"applied sensu client overrides","client":{"name":"HOSTNAME_REDACTED","address":"IP_REDACTED","subscriptions":["automation","client:HOSTNAME_REDACTED"]}}
{"timestamp":"2018-02-15T09:47:08.705184-0800","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
{"timestamp":"2018-02-15T09:47:08.705246-0800","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2018-02-15T09:47:08.705274-0800","level":"debug","message":"setting eventmachine threadpool size","size":22}
{"timestamp":"2018-02-15T09:47:08.719306-0800","level":"debug","message":"connecting to transport","name":"rabbitmq","settings":{"host":"SENSU_HOST_REDACTED","port":"PORT_REDACTED","vhost":"/VHOST_REDACTED","user":"USER_REDACTED","password":"PASSWORD_REDACTED","ssl":{"cert_chain_file":"/etc/sensu/ssl/cert.pem","private_key_file":"/etc/sensu/ssl/key.pem"}}}
{"timestamp":"2018-02-15T09:47:08.822810-0800","level":"debug","message":"transport connection open"}
{"timestamp":"2018-02-15T09:47:08.823034-0800","level":"debug","message":"binding client tcp and udp sockets","options":{"bind":"127.0.0.1","port":3030}}
{"timestamp":"2018-02-15T09:47:08.823348-0800","level":"debug","message":"binding client http socket","options":{"bind":"127.0.0.1","port":3031}}
{"timestamp":"2018-02-15T09:47:08.823472-0800","level":"debug","message":"scheduling keepalives"}
{"timestamp":"2018-02-15T09:47:08.823566-0800","level":"debug","message":"publishing keepalive","payload":{"name":"HOSTNAME_REDACTED","address":"IP_REDACTED","subscriptions":["automation","client:HOSTNAME_REDACTED"],"version":"1.1.3","timestamp":1518716828}}
{"timestamp":"2018-02-15T09:47:08.823732-0800","level":"debug","message":"subscribing to client subscriptions"}
{"timestamp":"2018-02-15T09:47:08.823807-0800","level":"debug","message":"subscribing to a subscription","subscription":"automation"}
{"timestamp":"2018-02-15T09:47:08.823966-0800","level":"debug","message":"subscribing to a subscription","subscription":"client:HOSTNAME_REDACTED"}
{"timestamp":"2018-02-15T09:47:08.824071-0800","level":"debug","message":"scheduling standalone checks"}
{"timestamp":"2018-02-15T09:47:28.824020-0800","level":"debug","message":"publishing keepalive","payload":{"name":"HOSTNAME_REDACTED","address":"IP_REDACTED","subscriptions":["automation","client:HOSTNAME_REDACTED"],"version":"1.1.3","timestamp":1518716848}}


So it looks like the list is empty. On restart, the log seems to indicate all the right subscriptions, etc but then the client ONLY runs standalone checks... I'll join the slack and try to work this out.

**Comment by portertech** [comment] 2018-02-26 17:01
This related sensu-client code in question 

"completing checks in progress": https://github.com/sensu/sensu/blob/e895d5958f1a3857601d3ef321f59dfc4d9e8f1f/lib/sensu/client/process.rb#L639-L642

"stopping reactor": https://github.com/sensu/sensu/blob/e895d5958f1a3857601d3ef321f59dfc4d9e8f1f/lib/sensu/daemon.rb#L215-L216

What's really bizarre is that `EM::stop_event_loop` should be immediately ending to process.

**Comment by rustygeldmacher** [comment] 2018-03-29 16:03
For what it's worth, we had a *very* similar problem -- all the checks were defined and the subscriptions were set up correctly, but for some reason Sensu stopped scheduling the checks.

The cause was that we had a rogue sensu-server process running in our environment, connected to the same transport as the real server. The rogue server had no checks defined and apparently when that happens no checks are scheduled even though there's a server that contains all the check definitions.

Removing the rogue server process brought everything back into sync. I hope this helps some other Googlers!

**Comment by ChrisOnToure** [comment] 2018-04-05 11:03
@rustygeldmacher Had the same issue. It would be nice to actually protect the cluster so no other sensu-servers can join and break things. Can be done by unicast IP or shared PW?

**Comment by mcbsdEU** [comment] 2018-04-05 13:38
Well, my personal opinion is that it is already protected. For sensu to be able to participate in communication, it needs to connect to rabbitmq...rabbitmq is password protected.
Situation might be different I admit when you have also client running there which is using same rabbitmq.json config. You can set-up check to monitor health api to check how many consumers are registered there. Etc for 3 sensu servers you would monitor for 3.
But I think it is quite possible for server admin to enable sensu-server process by purpose to dame something and it will leverage sensu-client settings...

**Comment by majormoses** [comment] 2018-04-26 18:18
As pointed out above there are already multiple forms of protections against a rouge sensu server from joining a cluster:
- rabbitmq username/password
- rabbitmq TLS certs
- rabbitmq vhost ACL's

Depending on how your setup is I would also suggest maybe restricting your firewalls (iptables, aws security groups, etc) to prevent nodes outside of the expected subnets from talking to RMQ.

My guess would be that you need to update your automation to not by default give credentials and certs that work in a real environment but should randomly/statically generate it for development/ci.

**Comment by cwjohnston** [comment] 2018-05-17 20:39
@anherrera have you been able to resolve this issue? Please let us know. If we haven't seen any update on this scenario by next week I think we'll close the issue due to inactivity.

**Comment by anherrera** [comment] 2018-05-19 20:35
I think I narrowed the issue down to rabbitMQ configuration being off. I'll let you know once new configs are in place whether this continues. Thanks for the followup.

**Comment by cwjohnston** [comment] 2018-08-02 19:54
I'm going to go ahead and close this for lack of update.

**Closed by cwjohnston** 2018-08-02 19:54 UTC
Labels: Triaged
