### ISSUE TITLE
Proxy requests: Client tokens not working

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1584] opened 2017-02-28 10:22 UTC
## Expected Behavior
Client tokens should be replaced by actual client variables

## Current Behavior
I tested this new interesting feature which I was waiting for and encountered following:
I have standard check with client tokens used inside. In the logs, check is published with tokens replaced but result is not.
Snip from Sensu Client logs (it is actually server itself, polling network devices via snmp):
...............
"message":"received check request","check":{"type":"standard","handlers":["default"],"command":"/opt/sensu/embedded/bin/check-graphite-data.rb -v -s https://xyz -u user -p userpass -t 'nPercentile(production.sw01.cpu.cpu1.5min,90)' -w 70 -c 80 -f '-60min'"
...............
"message":"publishing check result","payload":{"client":"sensu01","check":{"type":"standard","handlers":["default"],"command":"/opt/sensu/embedded/bin/check-graphite-data.rb -v -s https://xyz -u user -p userpass -t 'nPercentile(:::environment:::.:::name:::.cpu.cpu1.5min,90)' -w 70 -c 80 -f '-60min'"
...............
As a result, event is created because graphite receives target with name of the tokens which of course has no sense for it and therefore throws error.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Create proxy request check with tokens inside
2. Observe behaviour, check logs - if command itself is executed with replaced tokens or still with token names

## Context
Not usable right now.

## Your Environment
* Sensu version used: 0.28
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

Maybe I did something wrong... but seems check definition is pretty simple...
Thanks!

**Comment by cwjohnston** [comment] 2017-02-28 16:49
Hi @mcbsdEU, can you please provide a copy of your check definition?

**Comment by mcbsdEU** [comment] 2017-03-01 08:26
Hi,
This is a check definition with some fields renamed but the point is still there:

{
  "checks": {
    "netcheck": {
      "type": "standard",
      "handlers": ["default"],
      "command": "/opt/sensu/embedded/bin/check-graphite-data.rb -v -s https://xyz -u user -p userpass -t 'nPercentile(:::environment:::.:::name:::.cpu.cpu1.5min,90)' -w 70 -c 80 -f '-60min'",
      "interval": 60,
      "subscribers": ["proxy_net"],
      "auto_resolve": false,
      "proxy_requests": {
        "client_attributes": {
          "name": "lab-ccs-sw-02"
        }
      }
    }
  }
}

**Comment by cwjohnston** [comment] 2017-03-01 18:14
Thanks for the update @mcbsdEU, I've reproduced the issue and it appears to be caused by Sensu client behavior which allows local check definitions to override pubsub execution requests for checks of the same name. 

I believe the fix is for this for local override to be skipped when the check includes proxy_request attributes. Marking this as a bug.

**Comment by cwjohnston** [comment] 2017-03-02 00:26
Closed by https://github.com/sensu/sensu/pull/1592, to be included in 0.28.1

**Closed by cwjohnston** 2017-03-02 00:26 UTC
Labels: Bug
