### ISSUE TITLE
Signature cannot be added afterwards

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#1363] opened 2016-07-08 07:41 UTC
I would like to add a signature to my clients in the future. The problem is that once a client is registered without a signature, you cannot add a signature afterwards:
```
{"timestamp":"2016-07-08T07:36:05.597084+0000","level":"warn","message":"not retrieving client from the registry","result":{"client":"i-12345678","check":{"command":"check-process.rb -f /run/nginx.pid -C 1","standalone":true,"handlers":["default"],"interval":60,"occurrences":5,"name":"nginx_process","issued":1467963365,"executed":1467963365,"duration":0.573,"output":"CheckProcess OK: Found 1 matching processes; pid /run/nginx.pid\n","status":0},"signature":"c32a558f2f6bdfasykmdsafkjkjf92ca72dd2"}}
```
It would be better if the sensu server would just add the new signature to the client of it does not have any signature yet. This would allow us to roll out this feature without deleting clients from the server...

**Comment by portertech** [comment] 2016-07-08 17:55
This should be the current behaviour, labeling as a bug.

**Comment by cwjohnston** [comment] 2016-08-11 16:25
I haven't been able to reproduce this in a simple test with no existing client data. I stood up a new VM, configured the server, api and client, validated the client had registered w/o signature. Subsequent to initial client registration, changing and removing the signature both caused keepalive and check events to be rejected, with "not updating client in the registry" warnings logged.

@runningman84 can you please provide more detail about reproducing this issue, e.g. which version(s) of Sensu you are running on client and server?

**Comment by runningman84** [comment] 2016-08-17 18:45
I haven't had this problem lately maybe it was already fixed?

**Comment by cwjohnston** [comment] 2016-08-17 19:49
Closing as cannot reproduce.

**Closed by cwjohnston** 2016-08-17 19:49 UTC
Labels: Bug
