### ISSUE TITLE
Sensu-agent crash, too many open files

### ISSUE THREAD

**Issue by powellchristoph** [sensu/sensu#911] opened 2015-03-30 15:07 UTC
Over the weekend, I had a Sensu agent crash. There was some disruptive network maintenance which severed the network connection between the agent and rabbitmq. The server sent out the appropriate 'no keep-alive' alert, but when network connectivity was restored the agent did not reconnect. Upon investigation, the agent had crashed with an error regarding too many open files.

OS: Ubuntu 14.04.1 LTS
Sensu: From the PPA, 0.16.0-1

From the logs, it took about 10 minutes for the agent to crash:
```
{"timestamp":"2015-03-30T05:41:04.197605+0000","level":"warn","message":"reconnecting to transport"}
{"timestamp":"2015-03-30T05:41:37.213645+0000","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-03-30T05:41:52.220627+0000","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-03-30T05:42:02.225527+0000","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-03-30T05:42:17.232354+0000","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-03-30T05:42:22.234799+0000","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-03-30T05:42:51.781549+0000","level":"info","message":"reconnected to transport"}
{"timestamp":"2015-03-30T05:42:52.248887+0000","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-03-30T05:42:52.249662+0000","level":"warn","message":"reconnecting to transport"}
{"timestamp":"2015-03-30T05:43:02.253917+0000","level":"error","message":"[amqp] Detected TCP connection failure"}

...repeated logs truncated

{"timestamp":"2015-03-30T05:52:49.691997+0000","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-03-30T05:52:49.968895+0000","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-03-30T05:52:50.486228+0000","level":"error","message":"[amqp] Detected TCP connection failure"}
{"timestamp":"2015-03-30T05:52:50.518571+0000","level":"error","message":"[amqp] Detected TCP connection failure"}
140292266288800:error:02001018:system library:fopen:Too many open files:bss_file.c:398:fopen('/etc/sensu/ssl/key.pem','r')
140292266288800:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
140292266288800:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
ruby: ssl.cpp:194: SslContext_t::SslContext_t(bool, const std::string&, const std::string&, bool, const std::string&): Assertion `e > 0' failed.
```

**Comment by warmfusion** [comment] 2015-04-15 08:15
If this is repeatable can you give the output of `lsof | grep sensu` which will show the open files related to sensu. It may reveal if the issue is due to sockets or stale file handles. 

I've seen similar issues with the ruby stomp gems when using heartbeats, so a `gem list ` may be useful too.

**Comment by powellchristoph** [comment] 2015-04-15 14:34
This was a unique set of events that I did not have control over, so I am sure if I could repeat it. Also, this only happened on one server. The other 30 appeared to recover properly.

```
gem list

    amq-protocol (1.9.2)
    amqp (1.5.0)
    async_sinatra (1.0.0)
    bigdecimal (1.2.0)
    childprocess (0.5.3)
    daemons (1.1.9)
    em-redis-unified (0.5.0)
    em-worker (0.0.2)
    eventmachine (1.0.3)
    ffi (1.9.6)
    io-console (0.4.2)
    ipaddress (0.8.0)
    json (1.7.7)
    minitest (4.3.2)
    mixlib-cli (1.5.0)
    mixlib-config (2.1.0)
    mixlib-log (1.6.0)
    mixlib-shellout (1.6.0)
    multi_json (1.10.1)
    ohai (6.16.0)
    psych (2.0.0)
    rack (1.5.2)
    rack-protection (1.5.3)
    rake (0.9.6)
    rdoc (4.0.0)
    sensu (0.16.0)
    sensu-em (2.4.0)
    sensu-extension (1.0.0)
    sensu-extensions (1.0.0)
    sensu-logger (1.0.0)
    sensu-plugin (1.1.0)
    sensu-settings (1.2.0)
    sensu-spawn (1.1.0)
    sensu-transport (2.4.0)
    sinatra (1.3.5)
    systemu (2.6.4, 2.5.2)
    test-unit (2.0.0.0)
    thin (1.5.0)
    tilt (1.4.1)
    uuidtools (2.1.4)
    yajl-ruby (1.2.1)
```

**Comment by portertech** [comment] 2015-04-22 05:45
We may need to do some more cleanup on reconnect, closing open files for things like SSL certificates etc 0_o

**Comment by portertech** [comment] 2015-04-22 07:11
Looks like we'll have to write/patch some cpp :-1:

**Comment by hvyas** [comment] 2015-05-07 18:35
We had the same kind of issue. Is there any updated/patched ver. available yet?

**Comment by portertech** [comment] 2015-05-07 18:35
Working on an eventmachine fix, will be in 0.19.

**Comment by hvyas** [comment] 2015-05-07 18:37
Thanks much  @portertech ! that was fast! :+1:

**Comment by portertech** [comment] 2015-07-27 17:44
https://github.com/openssl/openssl/blob/6218a1f57e7e25a6b9a798f00cf5f0e56a02ff31/ssl/ssl_rsa.c#L613 - doesn't seem to release/close the open file :(

**Comment by calebhailey** [comment] 2016-04-09 21:45
Closing due to inactivity, and because I believe we resolved all these issues last year. Please feel free to create a new issue if this matter is not resolved. #monitoringlove

**Closed by calebhailey** 2016-04-09 21:45 UTC

**Comment by RiRa12621** [comment] 2017-06-19 11:19
in which release would that be resolved ?
